* Deep Simplicity
Author: John Gribbin

- The simplicity of nature is not be measured by that of our conceptions
- Nature is simple only in its causes
- The laws will turn out to be simple

** Introduction: The Simplicity of Complexity
   - /Simple truths are eternal/
   - /Our lives are the mercy of complicated processes that produce dramatic changes out of the blue/
   - Most interesting question of all => how life could have emerged from non-life
   - =The most interesting question of all remain unanswered.=
   - Science made enormous progress largely by ignoring the complexities and focusing on the simple questions
   - Gravity crushes any structure out of existence
   - *It is the simplicity that underpins complexity*
   - *Chaos and complexity obey simple laws*
   - *The complicated behavior of the world we see around us is merely surface complexity arising out of deep simplicity*
   - All business of chaos and complexity is based on two simple ideas:
     - the sensitivity of a system to its starting conditions
     - feedback
   - There are simple truths underpinning chaos and complexity

** Order out of chaos
   - There are simple, orderly laws underpinning the confusion of the world
   - There are simple situations which have unpredictable outcomes
   - /Entropy measures the amount of order in a system/
   - +You can never put things back the way they used to be+
   - Life is creating order and structure out of disordered materials
   - In the real world, there is no such thing as a perfect insulator
   - The truth is there is no such thing as an isolated system (except for the entire Universe)
   - No system is ever in perfect equilibrium.
   - It may get very close to equilibrium - as close as you like, if you wait long enough - but the equilibrium is never literally perfect.
   - /We live in an orderly world/
   - Sirius - one of the nearest stars
   - Thermodynamics and the idea of increasing entropy are statistical ideas
   - The world is not deterministic in the simplest sense after all, and that chance and probability must be taken into account when trying
     to describe or calculate the behavior of macroscopic systems
   - chaotic and unpredictable fashion

** The Return of Chaos
   - Many systems in the real world are sensitive to their initial conditions and that they move away from those starting conditions in a non-linear fashion.
   - There is no way at all to predict or know the future except by watching the Universe evolve
   - In our everyday lives, most changes occur in a linear fashion
   - You should take nothing for granted.
   - The only system that can replicate the behaviour of the Universe in every detail, is the Universe itself.
   - Instability is the normal
   - Permanently stable orbits are the exception
   - The Universe is ignorant of its own future and is its own fastest simulator
   - A non-linear system may be either much more or much less than the sum of its parts.
   - A linear system is more or less equal to the sum of its parts
   - Non-linear things move very swiftly away from their starting points
   - In some circumstances we cannot calculate just how a system will change as time passes because the information we have
     about it's starting conditions is not accurate enough
   - Small differences in the initial conditions produce very great ones in the final phenomena
   - *Deterministic universe could never be predicted in practice, either forwards or backwards*
   - The observations were neither sufficiently comprehensive nor sufficiently precise
   - Linear forecasting techniques were far from perfect.
   - Linear equations are easier to work with than non-linear equations.
   - toy models = simplifications
   - Butterfly effect => the sensitivity of the weather (and other complex systems) to initial conditions
   - The errors and uncertainties inherent in the observations matter significantly
   - The underlying simplicity from which chaos and complexity emerge:
     - simple laws
     - non-linearity
     - sensitivity to initial conditions
     - feedback
   - *Simple laws, non-linearity, sensitivity to initial conditions and feedback are what make the world tick*
   - Resonance - way of getting a large return for a relatively small effort, by making the effort at just the right time and pushing a system the way it wants to go
   - *We owe our existence directly to the effects of chaos at work in the asteroid belt*
   - The orbits of the planets are technically chaotic
   - obliquity - angle of tilt of a planet
   - pi - irrational number
   - *Time cannot, in principle, be reversed*
   - *The Universe cannot, in principle, be predicted in all its details*
   - *Chaos is inevitable*
   - No computer can be bigger than the entire universe
   - *The complexity of the universe is based on the deep simplicity*
   - *The complexity of the universe has emerged from the chaos*
   - *Life itself has emerged from the chaos*

** Chaos out of order
 - *Understanding the emergence of life is the utimate aim*
 - an unbroken chain of cause and effect
 - The road to chaos involves an infinite no of choices operating on an infinitely small scale
 - logistic equation = describes how the population of a species changes from one generation to the next
 - *In the midst of order there is chaos; in the midst of chaos there is order*
 - It is overwhelmingly more likely that a system will fall in to the chaotic regime
 - A completely random iterative process obeying a very simple rule has built up a fractal pattern
 - *It is randomness plus a simple iterative rule (or rules) that makes the complexity of the world*
 - complex numbers => 2D, everyday numbers => 1D
 - *Complexity arises from simplicity*
 - *The way to make complex structures out of simple rules is repetition*
 - *The underlying simplicity of the world can produce complex structures*
 - Near fractal self-similarity is a pervasive feature of the bodies of living organisms
 - *Complexity lives at the edge of chaos*
 - The most complex and interesting things in the universe are happening right at the end of chaos, just before order is destroyed.

** The Edge of Chaos

 - *The nearest a living thing ever gets to equilibrium is when it dies*
 - The gravitational force between two objects diminishes as they get further apart
 - Energy flowing through an open system and being dissipated
 - The gravitational energy of any object that has mass is negative
 - More compact object -> more negative its gravitational energy
 - The amount of gravitational energy stored in a collection of objects depends on the force between them.
 - *Universe could have appeared out of nothing at all*
 - A star might be created out of nothing at all
 - The Universe started out from the big bang in a very uniform state
 - Light takes a finite time to travel through space
 - Time elapsed since the Big Bang - 14 billion years
 - *The Universe is not in thermodynamic equilibrium*
 - It is gravity that tells the arrow of time which way to point
 - There are systems which cannot be compressed algorithmically and whose most compact representation are themselves
 - *The shortest description of the Universe is the universe itself*
 - The impetus to computer development was provided by the code-breaking work
 - Neural networks - any sufficiently complex mechanical system could learn from experience without actually being programmed by an outside intelligence
 - Life molecule - the double helix structure of DNA
 - Catalyst !== Inhibitor
 - Catalysis - The presence of a particular chemical substance (the catalyst) encourages a particular chemical reaction to take place
 - autocatalysis - positive feedback at work in a non-linear process
 - Enzymes = protein molecules
 - the reactions involve feedback and non-linearity
 - What seems to be a complicated pattern of self-organization can be explained in terms of a few simple interactions
 - *It is certainly always advisable to choose the simplest solution unless there are overwhelming reasons not to*
 - It is not quite always true in science that the simplest solution to a problem is certain to be the right one
 - Ockham's Razor - entities ought not to be multiplied except of necessity
 - Ockham's Razor - extremely reliable rule of thumb in most circumstances
 - *Not every feature of anatomy has to be adaptive*
 - External form seems to be under the control of simple chemical process
 - genetics = nature, environment = nurture
 - Evolution is a fact, a process seen  at work both in living organisms today and in the fossil record
 - Darwin's theory -> Evolution, Newton's theory -> Gravity
 - We do not yet have an evolutionary equivalent of Einstein's theory of gravity
 - *Variety is not just the spice of life; it is at the very heart of how life works*
 - The Turing mechanism occur in dissipative systems at the edge of chaos
 - Sometimes, small changes in the environment or small mutations can have big effects on the body form that develops
 - Small random changes can also have either big or small effects in the world at large
 - To understand how evolution takes place we must understand the morphogenetic processes involved

** Earthquakes, extinctions and emergence
 - We are the natural expression of the deeper order
 - 1/f noise contains information
 - The noise in the weather system is 1/f noise
 - It is so important to look at long term trends not just one-off events
 - Earthquakes obeying a power law
 - We are on the trail of a deep truth
 - We can begin to understand what is going on by looking at simpler systems, starting with one that also involves people
 - Good models are sufficient to give an insight into what's going on
 - Large events can happen out of the blue as a consequence of small triggers
 - Stock market fluctuations behave as 1/f noise
 - Economies are actually self-organizing systems on the edge of chaos
 - Any single event might be a special case and doesn't on its own tell you anything much about the underlying cause of similar events
 - We are dealing with a complex system - life on Earth - which is self-organizing, feeding off a flow of energy and exists at the edge of chaos
 - You do not need a larger trigger in order to set off a large event.
 - It is all built on networks, interconnections between the simple parts that make up a complex system
 - chaos, complexity and self-organized criticality
 - The way life arose is a phase transition in a chemical system involving a sufficient number of connections between the nodes of the network
 - The complexity of living things may very well be based on deep simplicity
 - Genes acto to control the machinery of the cell
 - Different kinds of cells are specialized for different tasks
 - There have only been about 4 x 10^17 seconds since the Big Bang in which the Universe was born
 - *Interesting things happen at the edge of chaos*
 - Feedback is an essential ingredient, in what makes them interesting
 - No of genes is directly proportional to the amount of DNA
 - Creatures like us are the most complicated systems in the universe
 - provocative and persuasive ideas of cell differentiation and development
 - *The most complicated systems in the Universe are built upon very simple rules*
 - the deep simplicity of the world

** The Facts of Life
 - Evolution is a fact of life
 - *The stable scenario is not necessarily the best scenario*
 - widening ripple of interactions
 - Evolution by natural selection will ensure that a change which is detrimental to the species involved will be washed away over the generations
 - A change that is beneficial  will spread and by spreading it will open up more networks pushing the system towards the edge of chaos
 - *Complex systems naturally evolve towards the phase transition at the edge of chaos*
 - In the static regime, nothing changes
 - In the chaotic regime, the changes are so rapid that nothing interesting can ever get time to happen
 - All species must evolve as fast as they can just to keep up with other species
 - The cut and try of evolution is not just to build a good animal, but to find good building blocks that can be put together to make many good animals
 - Species get neither better at surviving nor worse as time passes; they die off at random
 - *The struggle for survival is just as hard as it used to be*
 - *Successful species actually get better at evolving as time passes*
 - Evolution operates at the level of the individual
 - Change happens only slowly from one generation to the next
 - Sparsely connected networks naturally evolve to such a state with intervals of equilibrium punctuated by intervals of change
 - Earthquakes always begin at the point where the strain that has built up first exceeds some critical threshold
 - Simple models do give a good description of the real world
 - *The test of a good model is not how simple it is, but how well it provides insight into real systems*
 - the underlying simplicity of the worlk
 - All of the different effects produce the same pattern.
 - When the physical environment changes, the fitness landscape changes
 - The physical environment and the biological environment are interconnected much more subtly than it seems at first sight

** Life Beyond
 - Previously we were looking at life from the inside out
 - Now we are going to look at life from the outside in
 - Best way to look for entropy reduction -> measure the chemical composition of the atmosphere
 - independently minded and non-conformist
 - No life - gases in the atmosphere would be in a state of thermodynamic or chemical equilibrium
 - Life - waste products would be dumped and lower the entropy
 - An experiment that look for the general attributes of life, rather than specific kinds of life
 - Living systems characteristically bring local order  to systems, making entropy run backwards as long as they have
	 an external source of energy to feed on
 - A simple analysis of sound patterns could reveal the presence of life
 - Negative entropy = Information
 - *Nothing interesting happens in thermodynamic equilibrium*
 - Without the intervention of life all the oxygen in the atmosphere would get locked away in less than 10 million years
 - *The behavior of life on Earth alters the physical landscape*
 - Liquid water and life existed on the surface of our planet by 4 billion years ago
 - *An hypothesis is an idea about how things might work, it has not been tested by experiment and observation*
 - *Surface complexity is built upon foundations of deep simplicity*
 - The story of life in the Universe is another example of surface complexity built upon foundations of deep simplicity
 - 4 most common reactive elements - Carbon, Hydrogen, Oxygen and Nitrogen (CHON)
 - Proteins of all living things on earth are composed of various combinations of just 20 amino acids
 - *The boundary between life and non-life is blurred*
 - There is nothing unusual about life in the context of the way the Universe works
 - It is natural for simple systems to organize themselves into networks at the edge of chaos
 - Interferometry - data from several small telescopes are combined to mimic the observing power of one much larger telescope
 - Earth is the brightest planet in the solar system
 - *Life is entropy-reduction process*
 - Simple underlying causes can produce surface complexity
 - Chaos and complexity combine to make the universe a very orderly place, just right for life-forms like us.
 - *We are made in the image of the Universe itself*
