* Deep Simplicity
Author: John Gribbin

- The simplicity of nature is not be measured by that of our conceptions
- Nature is simple only in its causes
- The laws will turn out to be simple

** Introduction: The Simplicity of Complexity
   - Simple truths are eternal
   - Our lives are the mercy of complicated processes that produce dramatic changes out of the blue
   - Most interesting question of all => how life could have emerged from non-life
   - The most interesting question of all remain unanswered.
   - Science made enormous progress largely by ignoring the complexities and focusing on the simple questions
   - Gravity crushes any structure out of existence
   - *It is the simplicity that underpins complexity*
   - *Chaos and complexity obey simple laws*
   - *The complicated behavior of the world we see around us is merely surface complexity arising out of deep simplicity*
   - All business of chaos and complexity is based on two simple ideas:
     - the sensitivity of a system to its starting conditions
     - feedback
   - There are simple truths underpinning chaos and complexity

** Order out of chaos
   - There are simple, orderly laws underpinning the confusion of the world
   - There are simple situations which have unpredictable outcomes
   - Entropy measures the amount of order in a system
   - You can never put things back the way they used to be
   - Life is creating order and structure out of disordered materials
   - In the real world, there is no such thing as a perfect insulator
   - The truth is there is no such thing as an isolated system (except for the entire Universe)
   - No system is ever in perfect equilibrium.
   - It may get very close to equilibrium - as close as you like, if you wait long enough - but the equilibrium is never literally perfect.
   - We live in an orderly world
   - Sirius - one of the nearest stars
   - Thermodynamics and the idea of increasing entropy are statistical ideas
   - The world is not deterministic in the simplest sense after all, and that chance and probability must be taken into account when trying
     to describe or calculate the behavior of macroscopic systems
   - chaotic and unpredictable fashion

** The Return of Chaos
   - Many systems in the real world are sensitive to their initial conditions and that they move away from those starting conditions in a non-linear fashtion.
   - There is no way at all to predict or know the future except by watching the Universe evolve
   - In our everyday lives, most changes occur in a linear fashion
   - You should take nothing for granted.
   - The only system that can replicate the behaviour of the Universe in every detail, is the Universe itself.
   - Instability is the normal
   - Permanently stable orbits are the exception
   - The Universe is ignorant of its own future and is its own fastest simulator
   - A non-linear system may be either much more or much less than the sum of its parts.
   - A linear system is more or less equal to the sum of its parts
   - Non-linear things move very swiftly away from their starting points
   - In some circumstances we cannot calculate just how a system will change as time passes because the information we have
     about it's starting conditions is not accurate enough
   - Small differences in the initial conditions produce very great ones in the final phenomena
   - *Deterministic universe could never be predicted in practice, either forwards or backwards*
   - The observations were neither sufficiently comprehensive nor sufficiently precise
   - Linear forecasting techniques were far from perfect.
   - Linear equations are easier to work with than non-linear equations.
   - 

** Chaos out of order

** The Edge of Chaos

** Earthquakes, extinctions and emergence

** The Facts of Life

** Life Beyond
