* Four thousand weeks
Time and How to use it

Author: Oliver Burkeman

#+_begin_quote
It's the very last thing, isn't it, we feel grateful for: having happened. You know, 
you needn't have happened. You needn't have happened. But you did happen.
-- Douglas Harding
#+end_quote

#+begin_quote
What makes it unbearable is your mistaken belief that it can be cured. -- Charlotte Joko Beck
#+end_quote



** Part I: Choosing to choose

*** The Limit-Embracing life

*** The Efficiency Trap

*** Facing Finitude

*** Becoming a Better Procrastinator

*** The Watermelon Problem

*** The Intimate Interrupter

** Part II: Beyond Control

*** We Never Really have time

*** You are Here

*** Rediscovering Rest

*** The Impatience spiral

*** Staying on the Bus

*** The Loneliness of the Digital Nomad

*** Cosmic Insignificance Therapy

*** The Human Disease

** 10 tools for Embracing your finitude
 - Adopt a fixed volume approach to productivity
 - Serialize, serialize, serialize
 - Decide in advance what to fail at
 - Focus on what you have already completed, not just what is left to complete
 - Consolidate your caring
 - Embrace boring and single purpose technology
 - Seek out novelty in the mundane
 - Be a researcher in relationships
 - Cultivate instantaneous generosity
 - Practice doing nothing


- Life is a succession of transient experiences, valuable in themselves, which you will miss if you are completely focusing on the
	destination to which you hope they might be leading.
- Hard choices are unavoidable
- Tough choices are inevitable
- Seek out novelty in the mundane
- Denying reality never works
- Pay yourself first
- Limit your work in progress
- Resist the allure of middling priorities

** 3 rules of thumb especially useful for harnessing the power of patience as a creative force
 - Develop a taste for having problems
 - Embrace radical incrementalism
 - Originality lies on the far side of unoriginality

- *Broken fantasy* => you might one day finally reach the state of having no problems whatsoever

- The state of having no problems is obviously never going to arrive

- A life devoid of all problems would contain nothing worth doing and would therefore be meaningless.

- The presence of problems in your life is not an impediment to a meaningful existence, but the very substance of one.

- The presence of problems in your life is the very substance of a meaningful existence.

- Life is just a process of engaging with problem after problem

- Critical aspect of radical incrementalist approach -> to be willing to stop when your daily time is up, even
when you are bursting with energy and feel as though you could get much more done

- Stopping helps strengthen the muscle of patience that will permit you to return to the project again,
and thus to sustain your productivity over an entire career.

- Stay on the bus, stay on the fucking bus.

- The distinctive work begins at all only for those who can muster the patience to immerse themselves in the earlier stage -
the trial-and-error phase of copying others, learning new skills and accumulating experience.

