* Freedom from the known
Author: J.Krishnamurti

- We are human beings, not labels
- The World we live in clearly calls for a new planetary mentality if it is to avoid new and worse strife
- We live in a time of growing interdependence
- All the problems are interconnected and demands unprecedented international cooperation
- The mind is capable of producing harmony between nations
- *The same basic underlying psychological processes, the same flawed perceptions prevail and drive us all*
- A major obstacle is when we misapply thought based on past experience to a completely new challenge that demands
	to be looked at totally new
- What is important is not philosophy, ideology or belief but observing what is actually taking place in
	our daily life inwardly and outwardly
- When something serious is really understood, it naturally translates into action, action that
	can be liberating and joyful
-

** Man's search - The Tortured Mind - The Traditional Approach - The Trap of Respectability -

** The Human Being and the Individual - The Battle of Existence - The Basic Nature of Man - Responsibility

** Truth - Self-transformation - Dissipation of Energy - Freedom from Authority
 - Man has throughout the ages bas been seeking something beyond himself, beyond material welfare
 - *Living is a constant battle*
 - *A tortured mind however long it seeks will find only according to its own distortion
 - Individual => local entity - the little conditioned miserable, frustrated entity satisfied with his
	 little gods and his little traditions
 - Human being => not a local entity - is concerned with the total welfare, the total misery and total
	 confusion of the world
 - *The structure of society throughout the world has been created by individuals*
 - The outward social structure is the result of the inward psychological structure of our human relationships
 - *The individual is the result of the total experience, knowledge and conduct of a man*
 - the endless divisions of religion, ideology and nationality
 - with a sense of deep abiding frustration
 - the enormous confusion of life
 - a timeless state
 - *Faith invariably breeds violence*
 - We look to someone to tell us what is right or wrong behavior, what is right or wrong thought
 - Our conduct and our thinking become mechanical
 - We live on words
 - *Our life is shallow and empty*
 - *We are the result of all kinds of influences and there is nothing new in us*
 - A tortured mind, a broken mind, a mind which wants to escape from all turmoil
 - competitive existence
 - The world accepts and follows the traditional approach
 - *The primary cause of disorder in ourselves is the seeking of reality promised by another.*
 - A respectable human being cannot possibly come near to that infinite, immeasurable reality
 - the stupidity and immaturity
 - First thing to learn => not to seek
 - *Immaturity lies only in total ignorance of self*
 - *To understand yourself is the beginning of wisdom*
 - *In the greater, the lesser is, but in the lesser the greater is not*
 - collosally greedy
 - *We are both violence and peace*
 - We are strange mixture of hate, fear and gentleness
 - *Psychologically the individual has not changed at all*
 - We are frightened also of the unknown - frightened of death, frightened of what lies tomorrow
 - *We are afraid of the known and afraid of the unknown*
 - We are totally responsible for the whole state of the world
 - *Truth is something living, moving which has no resting place*
 - You and I are responsible for all this existing chaos
 - *There is not outer and inner process; there is only one unitary process*
 - monstrous society
 - *Truth has not path and that is the beauty of truth, it is living*
 - A dead thing has a path to it because it is static
 - There is only you
 - *All ideologies are utterly idiotic*
 - There is no guide, no teacher, no authority
 - Normally we thrive on blaming others, which is often  a form of self-pity
 - *The intellect is not the whole field of existence*
 - What is important is not a philosophy of life but to observe what is actually taking place in our
	 daily life inwardly and outwardly.
 - Nobody need to tell you how to look. You just look.
 - The intellect is a fragment, and a fragment is still a small part of existence,
	 whereas we have to deal with the totality of life.
 - double life between the ideology of the system and the actuality of your daily existence
 - fundamental revolution
 - *What is actually true is not the ideology but what you are*
 - You have to discard the dead weight of authority
 - Authority can never bring about inward order
 - Order imposed from without must always breed disorder
 - When there is freedom, there is energy
 - *Freedom is entirely different from revolt*
 - *A mind that has no fear is capable of great love*
 - We are living things always moving, flowing  never resting
 - The authority of yesterday is as destructive as the authority of a 1000 years
 - Forget all you know about yourself
 - Forget all you have every thought about yourself
 - We are going to start as if we knew nothing
 - *Be free of all authority*
 - We cannot be burdened with opinions, prejudices and conclusions
 - remembrance of yesterday
 - *It is vital that we understand ourselves*
 - Our responses to every problem are conditioned

** Learning about Ourselves - Simplicity and Humility - Conditioning
 - *There is no path to reality any more than to truth*
 - *You have to be your own teacher and your own disciple*
 - intelligent enquiry
 - Face the fact; look at it, do not run away from it. The moment you run away fear begins
 - There is no difference between the individual and the collective
 - You cannot exist by yourself
 - *Learning about yourself is always in the present*
 - *Knowledge is always in the past*
 - A mind that is burdened with the past is a sorrowful mind
 - *Acquiring knowledge about yourself and learning about yourself are two different things*
 - The moment you have achieved anything, you cease to have that quality of innocence and humility
 - *Our responses to every problem are conditioned*
 - *It is one of the most difficult things in the world to look at anything simply*
 - In order to understand ourselves we need a great deal of humility
 - If you have no foothold, if there is no certainty, no achievement, there is freedom to look to achieve
 - *When you look with freedom it is always new*
 - You respond to every challenge according to your conditioning and your conditioning being inadequate will always react inadequately
 - conditioning -> sense of imprisonment
 - You will be able to see for yourself how you are conditioned only when there is a conflict in the continuity of pleasure
	 or the avoidance of pain
 - When there is a disturbance, then you know you are conditioned
 - There is a tendency in all of us to put up with things
