* Good Strategy Bad Strategy
Author: Richard Rumelt

** Introduction - Overwhelming Obstacles
- Good strategy is almost looks this simple and obvious
- Strategy is not:
	- ambition
	- determination
	- inspirational leadership
	- innovation
- Ambition is drive and zeal to excel
- Determination is commitment and grit
- Innovation is the discovery and engineering new ways to do things
- Pivot points => multiply the effectiveness of efforts
- Core of strategy work:
	- discovering the critical factors in a situation
	- designing a way of coordinating and focusing actions to deal with those factors
- *A good strategy recognizes the nature of the challenge and offers a way of surmounting it*
- *Simply being ambitious is not a strategy*
- A good strategy does more than urge us forward toward a goal or vision
- A good strategy honestly acknowledges the challenges being faced  and provides an approach to overcoming them
- Good strategy is the exception not the rule
- The plentitude has not bought clarity
- Strategy cannot be a useful concept if it is a synonym for success
- Strategy cannot be a useful tool if it is confused with ambition, determination, inspirational leadership and innovation
- Strategy is about how an organization move forward
- A good strategy includes a set of coherent actions
- A strategy that fails to define a variety of plausible and feasible immediate actions is missing a critical component.
- Doing strategy => figuring out how to advance the organization's interests
- Kernel => an essential logical structure of good strategy
	- diagnosis
	- guiding policy
	- coherent action
- The creeping of bad strategy affects us all
- wishful thinking
- Our education system is rich with targets and standards, but poor in comprehending and countering the sources of underperformance
- *A good strategy creates strength through the coherence of its design*

** Good Strategy Bad Strategy
 - Most basic idea of strategy => application of strength against weakness
 - Strength applied to the most promising opportunity
 - Pursuing multiple objectives that are unconnected or conflict with one another
 - *The most powerful strategies arise from game changing insights*
 - 
*** Good Strategy is unexpected
  - A good strategy has
		- coherence
		- coordinating actions
		- policies
		- resources
	- substance and coherence of his insight
	- Most organizations will not create focused strategies
	- Good strategy requires leaders who are willing and able to say no to a wide variety of actions and interests
	- Having conflicting goals, dedicating resources to unconnected targets, and accommodating incompatible interests
	  are the luxuries of the rich and powerful, but they make for bad strategy
	- 
*** Discovering Power
  - The second natural advantage of many good strategies comes from insight into new sources of strength and weakness
	- *Our preconceived ideas about strength and weakness may be unsound*
	- The creation or revelation of a decisive asymmetry
	- a subtle shift in point of view
	- The terrible simplicity of the discovery of hidden power in a situation
	- to impose asymmetric costs on an opponent
	- the discovery of hidden power
	- Identify your strengths and weaknesses
	- Assess the opportunities and risks (opponent's strength and weakness)
	- Build on your strengths
	- 
*** Bad Strategy
  - Bad strategy grows out of specific misconceptions and leadership dysfunctions
	- Bad strategy => statements of desire
	- Good Strategy => plans for overcoming obstacles
	- Many bad strategies are statements of desire rather than plans for overcoming obstacles
	- Four hallmarks of bad strategy:
		- *Fluff* - Fluff is a form of gibberish masquerading as strategic concepts or arguments
			It uses 'Sunday' words and apparently esoteric concepts to create the illusion of high-level thinking
		- *Failure to face the challenge* - Bad strategy fails to recognize or define the challenge.
			When you cannot define the challenge, you cannot evaluate a strategy or improve it
		- *Mistaking goals for strategy* - Many bad strategies are just statements of desire rather than
			plans for overcoming obstacles
		- *Bad strategic objectives* - A strategic objective is set by a leader as a means to an end. Strategic
			objectives are "bad" when they fail to address critical issues or when they are impracticable
	- No challenge -> No strategy
	- Sunday words => words that are inflated and unnecessaryily abstruse
	- There had been a general decline in competence at understanding and formulating strategy
	- The basic problem is confusion between strategy and strategic goals
	- the lack of substance and coherence
	- a plentitude of vague aspirations
	- Bad strategy is not the same thing as no strategy or strategy that fails rather than succeeds
	- *Fluff is a superficial restatement of the obvious combined with a generous sprinkling of buzzwords*
	- Bad strategy puts forward strategic objectives that are incoherent and sometimes totally impracticable
	- Fluff masquerades as expertise, thought and analysis
	- Bad strategy is long on goals and short on policy and action
	- Hallmark of true expertise and insight => making a complex subject understandable
	- Hallmark of mediocrity and bad strategy => unnecessary complexity
	- A strategy is a way through a difficulty, an approach to overcoming an obstacle and a response to a challenge.

*** Why so much Bad Strategy?
 - Bad strategy flourishes because it floats above analysis, logic and choice
 - Bad strategy is the active avoidance of the hard work of crafting a good strategy
 - Strategy -> Focus -> Choice
 - Choice => setting aside some goals in favor of others
 - Disciplined conflict calls forth stronger evidence and reasoning
 - Bad strategy => avoiding the hard work of choice
 - Good strategy is very hard work
 - The essential difficulty in creating strategy is not logical; it is choice itself.
 - It would take enormous political will and the exercise of great centralized power to overcome the present level of institutional resistance
 - Universal buy-in usually signals the absence of choice
 - a crisis of epic proportions
 - The longer a pattern of activity is maintained, the more it becomes entrenched and the more its supporting resource allocations are taken to be entitlements
 - *New structures are more malleable*
 - Effective leadership does not depend on charisma
 - Charisma by itself does not guarantee effectiveness as a leader
 - *Strategy is the craft of figuring out which purposes are both worth pursuing and capable of being accomplished.*
 - To achieve great ends charisma and visionary leadership must almost always be joined with a careful attention to obstacles and action*
 - *Leadership  and strategy are not the same thing*
 - Thought is not only power, it is also the form of things.
 - Put every negative thought our of your mind once and for all.
 - Pockets of outstanding competence mixed with luck
 - Ascribing the success to a vision, shared at all levels, rather than pockets of outstanding competence mixed with luck is a radical distortion of history.
 - realistic and pragmatic
 - *If you form and hold your intent long enough it becomes true*
 - critical thinking and good strategy
 - The broadcast of intention goes out and makes it happen
 - Process of refinement => thinking about your intention many many times
 - All analysis starts with the consideration of what may happen, including unwelcome events.
   - Forms of psychosis cannot be recommended as approaches of management or strategy
*** The Kernel of Good Strategy
 - The kernel of a strategy contains 3 elements:
   - A *diagnosis* that defines or explains the nature of the challenge. A good diagnosis simplifies the often overwhelming complexity of reality
     by identifying certain aspects of the situation as critical.
   - A *guiding policy* for dealing with the challenge. This is an overall approach chosen to cope with or overcome the obstacles identified in the diagnosis.
   - A set of *coherent actions* that are designed to carry out the guiding policy. These are steps that are coordinated with
     one another to work together in accomplishing the guiding policy.
**** Diagnosis
   - A great deal of strategy work is trying to figure out what is going on.
   - Not just deciding what to do, but the more fundamental problem of comprehending the situation.
   - Comprehending the situation is the more fundamental problem
   - Simplified model of reality allows one to make sense of the situation and engage in further problem solving.
   - The diagnosis for the situation should replace the overwhelmingly complexity of reality with a simpler story.
   - A diagnosis is generally denoted by metaphor, analogy or reference to a diagnosis or framework that has already gained experience.
   - *It is important to take a broader perspective.*
**** Guiding policy
   - Good guiding policies are not goals or visions or images of desirable end states.
   - Good guiding policies define a method of grappling with the situation and ruling out a vast array of possible actions
   - Good strategy is not just "what" you are trying to do. It is also "why" and "how" you are doing it.
   - Absent a good guiding policy, there is no principle of action to follow.
   - Without a guiding policy, actions and resource allocations would probably be inconsistent or incoherent,
     fighting with one another and canceling one another.
**** Coherent action
   - *Strategy is about action, about doing something.*
   - *The kernel of a strategy must contain action*
   - There must be enough clarity about action to bring concepts down to earth
   - *Without action, the world would still be an idea.*
   - It is the *hard craft* of strategy to decide which prioirity shall take precedence.
   - *There is no greater tool to sharpening strategic ideas than the necessity to act.*
   - The kernel of a strategy applies to any complex setting.
   - The actions within the kernel of a strategy should be coherent.
**** Coherence
   - Strategic coordination is coherence imposed on a system by policy and design
   - Many decisions are effectively made on a decentralized basis
   - Coordination interrupts and de-specializes people
   - frozen maladaptive stasis
   - Good strategy and good organization lie in specializing on the right activities and imposing only
     the essential amount of coordination
** Sources of Power
*** Using Leverage
*** Proximate Objectives
*** Chain-link Systems
*** Using Design
*** Focus
*** Growth
*** Using Advantage
*** Using Dynamics
*** Inertia and Entropy
*** Putting it together
** Thinking like a Strategist
*** The Science of Strategy
*** Using your head
*** Keeping your head
