* The Last Lecture
lessons in living

Author: Randy Pausch

Time is all you have and you may find one day that you have less time than you think.

** Introduction
   - honesty, integrity and gratitude
   - Engineering is not about perfect solutions; it is about doing the best you can with limited resources.
   - tinkering, rethinking and organizing
     #+BEGIN_QUOTE
     If you can dream it, you can do it - Walt Disney
     #+END_QUOTE
   - If you dispense your own wisdom, others often miss it; if you often wisdom from a third party, it seems less arrogant and more acceptable
   - Never make a decision until you have to
   - Just because you are in the driver's seat doesn't mean you have to run people over
   - balance between aspiration and pragmatism
   - It's important to have specific dreams
   - Have something to bring to the table, because that will make you more welcome
   - If you can find an opening, you can probablyfind a way to float through it.
   - When you are screwing up and nobody says anything to you anymore, that means they have given up on you.
   - You have got to get the fundamentals down, because otherwise the fancy stuff is not going to work.
   - When you see yourself doing something badly and nobody's bothering to tell you anymore, that's a bad place to be
   - Your critics are often the ones telling you they still love you and care about you and want to make you better
   - If you work hard enough there will be things you can do tomorrow, that you can't do it today
   - head fake - indirect learning
   - *Don't believe in the no-win scenario*
   - Tenacity is a virtue, but it's not always crucial for everyone to observe how hard you work at something.
   - The brick walls are there for a reason. They are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something.
   - Sometimes, the most impenetrable brick walls are made of flesh.
   - It's easy to look smart when you are parroting small people
   - 

** Really Achieving your childhood dreams

** Adventures... and lessons learned
- When you have a dire medical issue, it's tough to know how you are really faring emotionally
- Strengths that were also flaws
- an inflexible contrarian always spouting opinions
- a Dutch uncle - refers to a person who gives you honest feedback
- People are more important than things
- *Even the mundane could feel magical*
- the most formidable brick wall
- The brick walls are there to stop the people who dont' want it badly enough. They're there to stop the other people
- Brick walls are there for a reason. They give us a chance to show how badly we want something.
- Be supportive
- measured response rooted in upbringing
- You don't repair things if they still do what they are supposed to do
- *Not everything needs to be fixed*
- No matter how bad things are, you can always make things worse.
- At the same time, it is often within your power to make them better.
- Let's saddle up and ride
- with complete disregard for his own safety
- the meaning of sacrifice and the power of humility
- Learn to let some of the little stuff slide
- Don't let small things trip us up
- Focus on each day, rather than the negative things down the road.
- Live in the moment
- The Truth can set you free


** Enabling the dreams of others
- Time is finite
- Time must be explicity managed like money
- You can always change your plan, but only if have one
- Ask youself: Are you spending your time on the right things?

** It's about how to live your life

** Final remarks
