* The Last Lecture
lessons in living

Author: Randy Pausch

Time is all you have and you may find one day that you have less time than you think.

** Introduction
   - honesty, integrity and gratitude
   - Engineering is not about perfect solutions; it is about doing the best you can with limited resources.
   - tinkering, rethinking and organizing
     #+BEGIN_QUOTE
     If you can dream it, you can do it - Walt Disney
     #+END_QUOTE
   - If you dispense your own wisdom, others often miss it; if you often wisdom from a third party, it seems less arrogant and more acceptable
   - Never make a decision until you have to
   - Just because you are in the driver's seat doesn't mean you have to run people over
   - balance between aspiration and pragmatism
   - It's important to have specific dreams
   - Have something to bring to the table, because that will make you more welcome
   - If you can find an opening, you can probablyfind a way to float through it.
   - When you are screwing up and nobody says anything to you anymore, that means they have given up on you.
   - You have got to get the fundamentals down, because otherwise the fancy stuff is not going to work.
   - When you see yourself doing something badly and nobody's bothering to tell you anymore, that's a bad place to be
   - Your critics are often the ones telling you they still love you and care about you and want to make you better
   - If you work hard enough there will be things you can do tomorrow, that you can't do it today
   - head fake - indirect learning
   - *Don't believe in the no-win scenario*
   - Tenacity is a virtue, but it's not always crucial for everyone to observe how hard you work at something.
   - The brick walls are there for a reason. They are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something.
   - Sometimes, the most impenetrable brick walls are made of flesh.
   - It's easy to look smart when you are parroting small people
   - 

** Really Achieving your childhood dreams

** Adventures... and lessons learned
- When you have a dire medical issue, it's tough to know how you are really faring emotionally
- Strengths that were also flaws
- an inflexible contrarian always spouting opinions
- a Dutch uncle - refers to a person who gives you honest feedback
- People are more important than things
- *Even the mundane could feel magical*
- the most formidable brick wall
- The brick walls are there to stop the people who dont' want it badly enough. They're there to stop the other people
- Brick walls are there for a reason. They give us a chance to show how badly we want something.
- Be supportive
- measured response rooted in upbringing
- You don't repair things if they still do what they are supposed to do
- *Not everything needs to be fixed*
- No matter how bad things are, you can always make things worse.
- At the same time, it is often within your power to make them better.
- Let's saddle up and ride
- with complete disregard for his own safety
- the meaning of sacrifice and the power of humility
- Learn to let some of the little stuff slide
- Don't let small things trip us up
- Focus on each day, rather than the negative things down the road.
- Live in the moment
- The Truth can set you free


** Enabling the dreams of others
- Time is finite
- Time must be explicity managed like money
- You can always change your plan, but only if have one
- Ask youself: Are you spending your time on the right things?
- Develop a good filing system
- Rethink the telephone
- Delegate
- Take a time out
- It's never too early to delegate
- Time is all you have. And you mind find one day that you have less time than you think.
- Be more self reflective
- Learn how to judge yourself
- The only way any of us can improve is if we  develop a real ability to assess ourselves
- Did you recognize your true abilities?
- Do you have a sense of your own flaws?
- Are you realistic about how others view you?
- Enabling the dreams of others is even more fun.
- What your peers think is, by definition, an accurate assessment of how easy you are to work with
- Getting people to welcome feedback is the hardest thing
- Luck is indeed where preparation meets opportunity
- Smart is not enough
- incredibly appreciative
- efficiency freak 
- Think far beyond the obvious
- Teamwork is so central to success
- Take it up a notch
- explicit license to break the mold
- the mix of freedom and teamwork
- Everybody loves telling stories, it's one of the truly universal thing about our species.

** It's about how to live your life
- Inspiration is the ultimate tool for doing good
- Give yourself permission to dream
- *Achieving the maximum of human potential is how our greatest problems will eventually be solved.*
- Take an earnest person over a hip person every time, because hip is short-term, earnest is long-term
- earnest = long-term, hip = short-term
- Earnest people are very serious and sincere in what they do or say, because they think that their actions and beliefs are imporantant.
- Somehow, with the passage of time and the deadlines that life imposes, surrendering became the right thing to do.

*** Dont' complain, just work harder
- Too many people go through life complaining about their problems
- If you took one tenth the energy you put into complaining and applied it to solving the problem, you'd be surprised  by how well things can work out.
- incredible non-whining aura
- *Complaining does not work as a strategy*
- We all have finite time and energy
- Any time we spend whining is unlikely to help us achieve our goals. And it won't make us happier.
*** Treat the disease, not the symptom
*** Don't obsess over what other people think
    A substantial fraction of many people's days is spent worrying about what others think of them.
    If nobody every worried about what was in other people's heads we'd all be 33% more effective in our lives and on our jobs
*** 

** Final remarks
