* Living within Limits
  Author: Garrett Hardin

** Entangling alliances
*** The Challenge of Limits
    - Commmon sense is sometimes wrong
    - Money talks, silence can be bought
    - Some of our most deeply held views are not neat
    - Science and technology shook the foundations
    - Man is an optimistic animal
    - In the public mind, the limited worldview was replaced by a limitless worldview
    - The new  orientation was intoxicating
    - An element of behavior that is transferred from one culture to another is likely to suffer a sea change
    - *Freedom is the recognition of necessity*
*** Overpopulation: Escape to the stars?
    - No number is inherently "big" or "little", it is only in comparison with other numbers that it takes on the attribute of size.
**** Overpopulation is more than a scientific problem
     - The problem is one of understanding and controlling human behavior
**** Extraterrestrial Migration: Some Relevant Scientific Details
**** Human populaton: Growth  Outruns Solutions
   - Dreams and reality are so far apart
   - *Reductio ad paradoxum*:
     - A question is settled once and for all if it can be shown that the assumptions of the problem lead to a logical absurdity.
     - A subtle and powerful analytical technique of Euclidean geometry
   - Number crunching has become fashionable
   - The widespread reluctance to embrace logic is disquieting
   - We must uncover the reasons for sorrow before we can find a way  to free ourselves from it
**** Three approaches to reality
     - There is no royal road to the solution of problems, but it helps to have a checklist of viewpoints  to use in the process of discovery.
     - *Literacy*: management of printed material and mastery of spoken words
     - *Numeracy*: the practice and art of using numbers to resolve problems
     - Rhetorically it is easy to say that life and money are incommensurable.
     - In real life, justice demands that we somehow commensurate the incommensurable.
     - *Ecology* is an extensive science, one that attempts to take account of all the factors that are influential in a given situation.
     - It is not easy to define ecology in a way that is both neat and useful.
     - An ecologist tries to see the whole picture.
     - Since an ecologist runs great risks, he is likely to make great mistakes; but narrow answers are not enough.
     - The ecological thinker is haunted by the consequences of time.
     - The ecological thinker is not satisfied with a plan that looks good at first: he wants to know what will happen 
       over the course of a long period, if the plan is put into operation.
     - As they see the forest more clearly they will less often be distracted by the trees.
     - Seldom does a single attitude lead to the best answer to a problem. It is wise to challenge each proposed alteration with 
       this checklist of questions:
       - *The literate question*: "What are the right word?"
       - *The numerate question*: "What are the relevant numbers?"
       - *The ecolate question*: "And then what?"

*** Uneasy Litter Mates: Population and progress
    - Throughout history human exploitation of the earth has produced this progression: colonize--destory--move on
    - Man stalks across the landscape, and deserts follow in his footsteps

*** Population theory: Academia's Stepchild

*** Default Status: Making Sense of the World

*** The Ambivalent Triump of Optimism

*** Cowboy Economics versus Spaceship Ecology

*** What Malthus Missed

*** The Demostat

*** Generating the Future

*** Limits: A Constrained View

*** From Jevon's Coal to Hubbert's Pimple

*** 
** Looking for the Bluebird
*** Nuclear Power: A Nonsolution
*** Trying to escape Malthus
*** The Benign Demographic Transition
** Biting the bullet
*** Making Room for Human Will
*** Major Default Positions of Human Biology
*** Carrying Capacity
*** The Global Pillage: Consequences of Unmanaged Commons
*** Discriminating Altruisms
*** The Double C-Double P Game
*** Birth Control vs Population Control
*** Population Control: Natural versus Human
*** The Necessity of Immigration Control
*** Recapitulation and a Look Ahead
    - Temperance must be the guiding ideal.
    - Pure pronatalism and pure misanthropy are both suicidal in their thrust.
    - With population, as with most goods in life, a golden mean is to be sought.
    - An understanding of numbers and ratios is essential, but the level of mathematical ability is required within reach of most of humankind.
  
