* The Logic of Failure
How to detect and avoid error in complex situations
Author: Dietrich Dorner

** Introduction
 - We are distressed, however, if we overlook the obvious
 - The global interrelations of today make such dissension important everywhere
 - *The modern world is made up of innumerable interrelated subsystems, and we need to think in terms of these interrelationships*
 - It appears that very early on human beings developed a tendency to deal with problems on an ad hoc basis
 - *The need to see a problem embedded in the context of other problems rarely arose*
 - We have been turned loose in the industrial age equipped with the brain of pre-historic times
 - Our tendency to think in simple chains of cause and effect is genetically pre-programmed.
 - We have a strong tendency to visualize when we form hypotheses about the world and the events that take place within it
 - We have great difficulty grasping problems that cannot be visualized
 - *Our brains are not fundamentally flawed; we have simply developed bad habits*
 - Real improvement can be achieved, however, if we understand the demands that problem solving places on us and the errors
	 we are prone to make when we attempt to meet them
 - Thinking is always rooted in the total process of psychic activity
 - Thought is always rooted in values and motivations
 - We ordinarily think not for the sake of thinking but to achieve certain goals based on our system of values
 - *The conviction that our intentions are unquestionably good may sanctify the most questionable means*
 - Motivations provide equally ambiguous guidelines
 - *Failure does not strike like a bolt from the blue; it develops gradually according to its own logic*

** Some Examples

*** The Lamentable fate of Tanaland
 - The explanations for success and failure lie instead in certain patterns of thought
 - We cannot do just one thing
 - Whether we like it or not, whatever we do has multiple effects
 - *Failure to anticipate side effects and long-term repercussions was one reason for the failures*
 - Helplessness generates cynicism

*** The Not-Quite-So-Lamentable Fate of Greenvale
 - To propose a hypotheses is to understand reality
 - the capacity to tolerate uncertainty
 - It's hard not to see in behavior a refusal to recognise one's impotence and helplessness
 - A tendency to seek refuge in certainty and security

*** Chernobyl in Tanaland
 - Theoretical knowledge is not the same thing as hands-on knowledge
 - *We find an inability to think in terms of non-linear networks of causation rather than of chains of causation*
 - *We find an inability to properly assess the side effects and repercussions of one's behavior*
 - *We find a tendency under time pressure to apply overdoses of established measures*
 - no longer operating analytically but rather intuitively
 - difficulty in:
	 - managing time
	 - evaluating exponentially developing processes
	 - assessing side effects and long-term repercussions
 - a tendency to think in terms of isolated cause-and-effect relationships




** The Demands
 - complexity, intransparence, internal dynamics, incomplete or incorrect understanding of the system
 - More variables -> greater interdependence -> greater system complexity

*** Complexity
  - Complexity is the label we will give to the existence of many interdependent variables in a given system
	- Complex is not an objective factor but a subjective one
	- Complexity must be understood in terms of a specific individual and his or her supply of supersignals
	- It is misleading to postulate complexity as a single topic
	- Supersignals reduce complexity collapsing a number of features into one

*** Dynamics
  - Reality is not passive but to some degree active
	- We cannot wait forever before we act
	- What we really want to see may not be visible
	- we must often do with tentative solutions because time pressure forces us to act before we can gather complete information
		or outline a comprehensive plan

*** Intransparence
	- Intransparence thus injects another element of uncertainty into planning and decision making
	- Structural Knowledge => knowledge of how the variables in the system are related and how they influence one another

*** Ignorance and Mistaken Hypotheses
  - Reality model -> explicit and implicit
	- Explicit reality model - always available to the individual in a conscious form
	- Implicit reality model - with the individual himself unaware that he is operating on a certain set of assumptions
	- Implicit knowledge - intuition
	- Implicit knowledge can be very useful
	- Explicit knowledge though it can be verbalized, cannot always be made useful
	- *The ability to admit ignorance or mistaken assumptions is indeed a sign of wisdom*
	- Most individuals in the thick of complex situations are not, or not yet, wise
	- We must find a way to keep track of complicated interrelations and deduce development tendencies, sometimes armed with only sketchy information

*** Steps in Planning and Action
  - We need to have clear goals in mind before we start forming judgments and arriving at decisions
	- We are constantly deciding how much information is enough
	- When is a general grasp of salient points adequate?
	- When do we need to bring in a microscope?
	- Thinking in terms of developmental trends and understanding such trends will enable us to prepare for future events
	- Methodism => tendency to act in accordance with preestablished patterns
	- To be successful a planner must know when to follow established practice and went to strike out in a new direction
	- Plans must be translated into reality
	- Persistence often pace of
	- Taking the middle path between clinging stubbornly to a doomed plan and giving up a fundamentally good one at the first sign of difficulty is not easy
	- Are the premises for your actions correct?
	- We must be prepared to to acknowledge that a solution is not working
	- It is unwise however to abandon an established course of action too soon
	- We need a cohesive picture that lets us determine what is important and what is unimportant, what belongs together and what does not
	- Structural knowledge will allow us to find order in apparent chaos
	- 

** Setting Goals
 - To work toward a desirable state of affairs is a positive goal
 - to correct or prevent a deficient state of affairs is a negative goal
 - It is important to understand the link among goal criteria
 - We should always try to make general goals specific
 - Unless goals often contain multiple goals hidden within them
 - If we want to dispel the unclarity inherent in these complex concepts we must be deconstruct them
 - central and peripheral problems
 - Goals conflict with one another not by their very nature, but because the variables relating to them in the system are negatively linked
 - Ranking problems and delegating tasks are good strategies when we have more than one goal
 - Individual partial goals may be incompatible
 - Implicit goals are dangerous because they go unnoticed at the early stages of a planning process
 - The lack of knowledge is secondary
 - More important is that no one took the trouble to acquire the necessary knowledge
 - When we are working on a given problem we focus on that problem alone and not on problems that don't exist
 - The mistake is less not knowing then not wanting to know
 - Complex concept comprising many different components and their relationships to one another
 - Complex concept comprising many different components and their relationships to one another
 - Giving far too much attention to relatively unimportant problems and either over looking the truly important ones or failing to assess them properly
 - irrelevant criteria -
	 - the obviousness of a problem 
	 - our competence to solve it
 - If we act on the basis of a more or less randomly generated list of complaints we necessarily remain captives of the present moment
 - Human beings are constituted that they often find challenges attractive
 - *Success cannot be too certain or too unlikely*
 - Setting priorities by the Criterion of obviousness is not good
 - Selecting problems on the basis of your competence is also not good
 - A goal that remains unclear one that is not broken down into to concrete partial goals runs the risk of taking on a life of its own
 - An interim goal may dislodge the primary goal
 - We think we can find security in things that seem absolute and that protect us from all contradiction
 - We are infatuated with neat means, methods and techniques
 - Goals degenerate because of the Desire for safety and a lack of confidence in one's own capabilities
 - Inadequate analysis leads first of all to uncertainty
 - Realising we are attacking the wrong problems only makes us more on certain
 - If we have no criteria based on the specification of our goals to help us set priorities
	 - we will choose the most obvious problems or
	 - the ones that we already know how to solve
 - Repair service behaviour is surely preferable to correct obvious ills than to do nothing at all
 - Pragmatic politics not driven by the lofty ideals but by the exigencies of the situation
 - Pragmatic politics not driven by the lofty ideals but by the exigencies of the situation
 - If we formulate goals in concrete terms we should; if we cannot then muddling through is better than inaction
 - Something that doesn't cost much is rally of much benefit
 - *If you want to derive great benefit we usually have to investe a lot*
 - Contradictory goals are the rule not the exception in complex situations
 - Unrecognised contradictory relations between partial goals lead to actions that inevitable replace one problem with another
 - The verbal integrations of incompatibles can over time produce changes in the meanings of words
 - Our understanding of prevailing conditions is inadequate
 - It is difficult for us to admit to ourselves that despite the best of intentions we have failed
 - When we must deal with problems in complex systems few things are as important as setting useful goals
 - When we do not make overly General or unclear goals specific we are likely to spend time unwisely on ineffective repair service behaviour
 - Ultimately to salve our self confidence we may find ourselves choosing projects for their obviousness or ease rather than for their importance

*** Requirements of Goal setting

*** General Goals and "Repair Service" behavior

*** Liberty, Equality and "Voluntary Conscription"

** Information and Models
 - We can't focus only on what is wrong and what we want to correct
 - Most of the time the systemic nature of the situations was ignored
 - All effort had gone toward treating a symptom and none toward solving the underlying problem
 - A system is a network of many variables in causal relationships to one another
 - Within a system a variable may have a causal relationship to itself
 - It is usually wise when correcting a deficiency to consider it within the context of its system
 - *We may also overlook the unpleasant side effects of our actions and do more harm than good in the long run*
 - Positive feedback tends to undermine the stability of a system
 - It is obviously greatly to our advantage to look at a deficiency not in isolation but embedded in its system
 - We need to know more than just the causal relationships between individual variables in a system
 - *Knowledge of the constituent elements of a system can also give us important insights into the structure of that system*
 - Thinking by analogy => rather primitive and obvious step
 - It is essential to understand the relationships between broad and narrow concepts, between the Abstract and the concrete
 - *False hypotheses are better than no hypotheses at all because they can ultimately lead us to correct knowledge*
 - There is No a Priori appropriate level of detail
 - We should select the level of detail needed to let us understand the interrelationships among our goal variables
 - Goal variable are the variables we want to influence
 - *An important method to acquire knowledge about the structure of a system is analogy*

*** Reality, Models and Information

*** Solving problems one at a time
  - A bundle of independent mini systems
	- Take into account the side effects and repercussions of certain measures
	- If we do not concern ourselves with the problems we do not have, we soon how them
	- most of us lack an overall view of the system and of the reciprocal interactions with in it
  - The reason we deal with partial problems in isolation is our preoccupation with the immediate goals
	- It is obviously better if we know how the individual variables in the system relate to one another
	- Reductive hypothesis - tying everything to one variable
	- People use many dodges to defend their pet hypothesis  against logical argument or the evidence of experience
	- Reductive hypothesis provide simplest explanations for what goes on in the world accounts not only for their popularity but also for their persistence
	- Unsurveyability ->  uncertainty ->  fear
	- In extreme cases we may devise elaborate and dogmatic defences to protect hypotheses that in no way reflect reality
	- We are infatuated with the hypothesis we propose because we assume they give us power over things
	- Every situation has to be considered afresh
	- Context should determine strategy
	- *The world of our ideas is usually not particularly colourful*
	- Our ideas are pale outlines
	- *A necessary generalization can easily evolve into overgeneralization*
	- As a rule we have no opportunity to test in advance whether a concept we have developed has stuck just the right degree
		of abstraction or is an overgeneralization
	- deconditionalized concept - concept removed from the context of conditions bearing on it
	- *The effectiveness of a measure almost always depends  on the context within which the measure is pursued.*
	- |<--right degree of abstraction ------------------- abstraction spectrum --------------------- overgeneralization-->|
	- similarity matching - tendency to respond to similarities more than to differences
  - Before we apply an abstract concept to a concrete situation, we should submit it to strategic scrutiny to
    decide whether it is appropriate to the context
  - Strategy is a system of makeshifts. It is more than a science
  - Strategy is bringing knowledge to bear on practical life, the further elaboration of an original guiding idea
    under constantly changing circumstances.
  - A wise decision will always depend on the given constellation of conditions.
  - Everything is in flux, and we must adapt accordingly

*** "It's the Environment"

*** Prime Numbers and Tourist Traffic or Moltke and Forest Fires

*** The Pale Cast of Thought
  - A sensible and effective measure in one set of circumstances can become a dangerous course of action when conditions change
  - We must keep track of constantly changing conditions and never trust any image we form of a situation as permanent.
  - Before we make a generalization, we should consider whether we have enough evidence to do so.
  - *To the ignorant, the world works simple*
  - We realize how much we still don't know, and we feel a strong desire to learn more.
  - *The more we know, the more clearly we realize what we don't know*
  - New info muddies the picture
  - *In reality we rarely have complete information*
  - Once we finally reach a decision we are relieved to have the uncertainty of decision making behind us.
  - an inverse relationship between information gathering and readiness to act.
  - clear focus and clear shift in focus
  - *The excess information bred uncertainty*
  - We simply stop playing a game that makes us more and more uncertain and anxious and less and less capable of.
  - *Horizontal flight*: pulling back into a small, cozy corner of reality where we feel at home
  - *Vertical flight*: kicking ourselves free of recalcitrant reality altogether and constructing a more cooperative image of that reality
  - We combat our uncertainty either by acting hastily on the basis of minimal information or by gathering excessive information
    which inhibits action and may even increase our uncertainty.
  - 2 factors come together in extrapolations from the moment:
    - limited focus on a notable feature of the present
    - extension of the perceived trend in more or less linear and monotone fashion

** Time Sequences
 - We live and act in a 4 dimensional (4D) system : 3 dimensions of space + 1 dimension of time
 - The dimension of time moves in one direction, toward the future
 - We rarely have trouble dealing with configurations in space

*** Time and Space
  - A time configuration is available for examination only in retrospect
  - *Life forces us to understand patterns in time*
  - Space configurations can be perceived in their entirety while time configurations cannot
  - We often overlook time configurations and treat successive steps in a temporal development as individual events
  - We are constantly presented with whole spatial configurations, we readily think in such terms
  - Even when we think in terms of time configurations, our intuition is very limited
  - We seem to rely on only a few mechanisms of prognostication to gain insight into the future
  - Fixation on the characteristics of the moment brings with it the danger that too much significance is ascribed to present circumstances.
  - Fixation on linear future development may prevent us from anticipating changes in direction and pace.

*** Lilypads, Grains of Rice and AIDS
    - In a linear process, a quantity increases by the same amount, not same multiple at each step.
    - A incapacity to deal with nonlinear time configurations is a general phenomenon
    - We find unawareness of the explosive course exponential development can take
    - *People tend to badly misjudge non-linear growth*
    - Unfortunately, the complications of reality are even greater than simple exponential growth.
    - Exponential growth can occur only when completely unlimited resources are available.
    - We cannot interpret numbers solely on the basis of their size.

*** A Premature All Clear

*** Laymen and Experts
    - layman => linear-development model
    - professional => far wider range of mathematical growth functions
    - layman => implicit choice (feeling or intuition)
    - professional => conscious choice
    - Even rational professional prediction is prone to psychological weakness
    - 

*** "Twenty-eight is a good number"
    - Collapsed in helpless surrender to the incomprehensible ways of the system
    - Magical hypotheses are probably the result of overgeneralization on the basis of local experience
    - Sequential hypotheses arise from the conditionalizing of simple hypotheses
    - 2 modes of hypotheses formation:
      - generalizing from local experience
      - progressive conditionalizing of local experience to the point of ritualization
    - *In the real world, systems rarely provide us with complete information on the behavior over time*
    - In the real world, people tend even more to overgeneralize from local experience, to ritualize, and to 
      believe  that no rationally comprehensible principle is at work.

*** Predators and Prey
    - Catastrophes seem to hit suddenly, but in reality the way has been prepared for them.
    - Converting time into space seems to help people comprehend temporal configurations.
    - less burdened with information
    - Perhaps human being can learn how to deal with time configurations
    - *Information comes in isolated fragments*
    - lacks both continuity and constant correctives
    - focus on understanding developments
    - The system is characterized by some internal dynamics of some significance
    - dealing with a process in time
    - remains a captive of the moment
    - drastically underestimates the obvious and almost exponential growth
    - learns next to nothing
    - a strategy of aggressive countermeasures
    - counterproductive behaviours
    - *Reasonable behaviour is the rule rather than the exception*
    - Try to understand the internal dynamics of the process
    - Make notes on those dynamics so that you can take past events into account and not be at the mercy of the present moment
    - *Try to anticipate what will happen*

*** The Moths of Kuera

** Planning
*** Go Make Yourself a Plan
- *Essence of planning:* to think through the consequences of certain actions and see whether those actions will bring us closer to our desired goal.
- individual links in planning:
  - condition element
  - action element
  - result element
- forward planning => natural => act forward
- reverse planning => unnatural
- Theoretically, planning is a simple matter
- *A complete investigation of an entire problem sector is utterly impossible*
- problem sector => a sector of reality
- We can plan completely only rarely and in relatively uninteresting areas.
- common focusing procedure => Hill climbing
- Because the vastness of the problem sectors prohibits us from investigating them completely, we must narrow our focus.
- We must not succumb to methodism, choosing an action only because it has worked before
- Long association of a particular item with a particular function makes it difficult for us to imagine that item's  serving any other purpose
- *We often do not realize we are captives of our old ideas and are by no means considering all the available possibilites*
- *The most important method for expanding a problem sector is thinking by analogy*
- *Planning is a process of narrowing our problem sector*.
- Time limits may force us to develop only crude plans or may curtail planning altogether
- There are instances in which we should not overplan or even plan at all, regardless of the amount of time.
- Redundancy of potential command => Many individuals who are all capable of carrying out leadership tasks within
  the context of the general directives.
- a tendency to resort to centralized regimes in stressful situations
- We can make plans that are too crude and plans that are too detailed. The trick is to plan
  with an appropriate degree of detail.
- Complete planning should be tempered by the concept of nonplanning
- Planning can increase our insecurity rather than reduce it.
- *The difficulty of finding the correct scale for planning accounts for many failure.*
- More uncertain => greater tendency to overplan
- Looking closely at a problem often increases our insecurity
- Our diversionary planning process lets us off the hook for the time being and spares us the possibility of failure.
- *Overly detailed planning can have dire consequences*
- If we believe we have anticipated and prepared for all eventualities things can still go wrong.
- Planning unit:
  - condition
  - action
  - result
- *If we expect the unexpected , we are better equipped to cope with it.*
- Crude planning is, of course, just as dangerous as overly detailed planning.
- *What we do have to avoid is reducing and simplifying reality until we are able to fit it into a predetermined formal patterns.*
- Expect the unexpected
- Planning is much easier if we ignore the condition element and assume that our action is generally applicable.
- *We human beings tend to think in the abstract anyway.*
- We can describe our plans much more easily, but our description may conceal problems.
- In war everything is simple, but it's the simple things that are difficult.
- Discounting the conditions under which we will carry out our actions simplifies planning but not acting.
*** Rumpelstilskin
- Plans often fail because the planners have not factored in all the irksome little conditions or "frictions" that
  have to be dealt with if the plan is to succeed.
- The plan may be simple, but carrying it out is the hard part.
- Saw the route but not the obstacles
- It is when we have the big picture firmly in mind that we are most prone to forget about details
- Not taking frictions into account is a trap that experts are particularly apt to fall into.
- We would never accomplish anything if much of what we do were not preprogrammed.
- Oversimplifications, progressively corrected in subsequent development are the most potent or
  indeed the only means toward conceptual mastery of nature.
- *Experience does not always make us smart. Experience can also make us dumb.*
- The effects of methodism can have a significant impact.
- *Methodism*: the unthinking application of a sequnce of actions we have once learned.
- We are most inclined to deconditionalize a form of action and use it over and over again if it has
  proved successful for us or others.
- an infinite mass of minor events
- In many complex situations considering a few characteristic features of the situation and developing
  an appropriate course of action in the light of them is not the essential point.
- We will be all the more inclined to overestimate their efficacy.
- the common propensity for deconditionalized planning
- The bad problem solvers used "absolute" concepts that do not admit of other possibilities or circumstances
- The good problem solvers favored expressions that take circumstances and exceptions into account
- *Good problem solvers* => qualified expressions
- *Bad problem solvers* => unqualified expressions
- Even negative results provide us a chance to apply correctives and in that way help us improve our future behavior
- The differences are blatant
- When we obtain un unexpected result, we can ask ourselves whether we began with false premises or whether we had an
  incorrect or incomplete picture of reality
- Good planners => attempt to analyze and to find reasons
- Bad planners => use dogmatism and assertions instead of analysis
- Studying the consequences of our measures gives us excellent opportunities for correcting our incorrect
  behavioral tendencies and assumptions about reality
- *Sometimes decisiveness grows out of a conviction that we know what to do*

*** Learn by making Mistakes? Not Necessarily!
- Unexpected results should give us pause
- Why our image of reality is so far off the mark?
- Did we form incorrect hypotheses?
- People look for and find ways to avoid confronting the negative consequences
- As a general principle, behavior should be ballistic
  Because our grasp of reality can only be partial, we have to be able to adjust the course
  of our actions after we have launched them
- Analysing the consequences of our behavior is crucial for making these ex post facto adjustments
- If we never look at the consequences of our behavior, we can always maintain the illusion of our competence
- Ballistic behavior has the great advantage of relieving us of all accountability
- the treatment, consideration and disregarding of conditions in planning
- Activity may foster an illusion of competence
- *Ends justify means*
- less attention to overarching moral standards
- We can protect and maintain our competence by an immunizing marginal conditionalizing of our measures.
- marvelous method  for dispelling all doubts about our competence

** So Now what we do?
- inadequacies of human thought
- people fail to :
  - formulate goals in concrete terms
  - recognise when goals contradict
  - set clear priorities
- determine the main psychological reasons for these inadequacies
- *We humans are quite deft at many tasks*
- The need to economize, to save time and effort, underlies many of the failings in our thought process
- *economize* - to save time and effort
- Our tendency to economize prompts us to omit certain steps in the thought process or to simplify them,
  as much as possible plays a major role when we deal with complex situations.
- *We will simply refuse to look at the consequences of our actions*
- *We don't think about problems we don't have*
- We must think about problems we may not have at the moment but that may emerge as side effects of our actions
- *We are captives of the moment*
- *Operative intelligence* : the knowledge that individuals have about the use of their intellectual capabilities and skills
- Local rules to a large extent dictated by specific circumstances
- *The ability to deal with problems in the most appropriate way is the hall mark of wisdom rather than genius*
- Simple methods can improve our ability to think
- *We should reflect on our own thinking but with some guidance.*
- *The ability to talk about something does not necessarily reflect an ability to deal with it in reality.*
- *We have few opportunities to learn from our mistakes*
- Simulated scenarios are an excellent teaching device
- What we did yesterday is lost in the obscurity of the past, and what we ought to do tomorrow is in utter darkness.
- *We must learn to cope with side effects*
- *We must learn to think in terms of systems*
- Mistakes are essential to cognition
- Systemic thinking cannot be regarded as a single unit, as particular, isolated capability.
- Systemic thinking is a bundle of capabilities to apply our normal thought process, common sense to the circumstances
  of a given situation
- In the real world, expanses of time and space hide our mistakes from us.
- What matters is not, the development of exotic mental capabilities
- What matters is not full utilization of the neglected right half of the brain,
  not the liberation of some mysterious creative potential and not
  the mobilization of that fallow 90% of our mental capacity.
- *The only thing that matters most* => the development of our common sense

**** Learnings
- We can learn that it is essential to state goals clearly. We all know we should do that, but we rarely encounter the necessity
- We can learn that we cannot always realize all our goals at once, because different goals may contradict one another. We
  must often compromise between different goals.
- We can learn that we have to establish priorities but that we cannot clint to the same priorities forever. We may have to change them
- We can learn that in dealing with a given configuration that we should form a model of the system. We must
  anticipate side effects and long-term repercussions and not just let them roll over us.
- We can learn how to adapt information gathering to the needs of the task at hand, neither going into excessive detail nor stopping too short.
- We can learn the consequences of excessive abstraction
- We can learn the consequences of hastily ascribing all events in a certain field  to one central cause.
- We can learn when to continue gathering information and when to stop.
- We can learn that we tend toward "horizontal" or "vertical" evasion and that the tendency can be controlled.
- We can learn that we sometimes act simply because we want to prove ourselves that we can act.
- We can learn the dangers of knee-jerk "methodism".
- We can learn that it is essential to analyze our errors and draw conclusions from them for reorganizing our thinking and behavior.


