* The Logic of Failure
How to detect and avoid error in complex situations
Author: Dietrich Dorner

** Introduction
 - We are distressed, however, if we overlook the obvious
 - The global interrelations of today make such dissension important everywhere
 - *The modern world is made up of innumerable interrelated subsystems, and we need to think in terms of these interrelationships*
 - It appears that very early on human beings developed a tendency to deal with problems on an ad hoc basis
 - *The need to see a problem embedded in the context of other problems rarely arose*
 - We have been turned loose in the industrial age equipped with the brain of pre-historic times
 - Our tendency to think in simple chains of cause and effect is genetically pre-programmed.
 - We have a strong tendency to visualize when we form hypotheses about the world and the events that take place within it
 - We have great difficulty grasping problems that cannot be visualized
 - *Our brains are not fundamentally flawed; we have simply developed bad habits*
 - Real improvement can be achieved, however, if we understand the demands that problem solving places on us and the errors
	 we are prone to make when we attempt to meet them
 - Thinking is always rooted in the total process of psychic activity
 - Thought is always rooted in values and motivations
 - We ordinarily think not for the sake of thinking but to achieve certain goals based on our system of values
 - *The conviction that our intentions are unquestionably good may sanctify the most questionable means*
 - Motivations provide equally ambiguous guidelines
 - *Failure does not strike like a bolt from the blue; it develops gradually according to its own logic*

** Some Examples
*** The Lamentable fate of Tanaland
 - The explanations for success and failure lie instead in certain patterns of thought
 - We cannot do just one thing
 - Whether we like it or not, whatever we do has multiple effects
 - *Failure to anticipate side effects and long-term repercussions was one reason for the failures*
 - Helplessness generates cynicism

*** The Not-Quite-So-Lamentable Fate of Greenvale
 - To propose a hypotheses is to understand reality
 - the capacity to tolerate uncertainty
 - It's hard not to see in behavior a refusal to recognise one's impotence and helplessness
 - A tendency to seek refuge in certainty and security

*** Chernobyl in Tanaland
 - Theoretical knowledge is not the same thing as hands-on knowledge
 - *We find an inability to think in terms of non-linear networks of causation rather than of chains of causation*
 - *We find an inability to properly assess the side effects and repercussions of one's behavior*
 - *We find a tendency under time pressure to apply overdoses of established measures*
 - no longer operating analytically but rather intuitively
 - difficulty in:
	 - managing time
	 - evaluating exponentially developing processes
	 - assessing side effects and long-term repercussions
 - a tendency to think in terms of isolated cause-and-effect relationships




** The Demands
 - complexity, intransparence, internal dynamics, incomplete or incorrect understanding of the system
 - More variables -> greater interdependence -> greater system complexity

*** Complexity
  - Complexity is the label we will give to the existence of many interdependent variables in a given system
	- Complex is not an objective factor but a subjective one
	- Complexity must be understood in terms of a specific individual and his or her supply of supersignals
	- It is misleading to postulate complexity as a single topic
	- Supersignals reduce complexity collapsing a number of features into one

*** Dynamics
  - Reality is not passive but to some degree active
	- We cannot wait forever before we act
	- What we really want to see may not be visible
	- we must often do with tentative solutions because time pressure forces us to act before we can gather complete information
		or outline a comprehensive plan

*** Intransparence
	- Intransparence thus injects another element of uncertainty into planning and decision making
	- Structural Knowledge => knowledge of how the variables in the system are related and how they influence one another

*** Ignorance and Mistaken Hypotheses
  - Reality model -> explicit and implicit
	- Explicit reality model - always available to the individual in a conscious form
	- Implicit reality model - with the individual himself unaware that he is operating on a certain set of assumptions
	- Implicit knowledge - intuition
	- Implicit knowledge can be very useful
	- Explicit knowledge though it can be verbalized, cannot always be made useful
	- *The ability to admit ignorance or mistaken assumptions is indeed a sign of wisdom*
	- Most individuals in the thick of complex situations are not, or not yet, wise
	- We must find a way to keep track of complicated interrelations and deduce development tendencies, sometimes armed with only sketchy information

*** Steps in Planning and Action
  - We need to have clear goals in mind before we start forming judgments and arriving at decisions
	- We are constantly deciding how much information is enough
	- When is a general grasp of salient points adequate?
	- When do we need to bring in a microscope?
	- Thinking in terms of developmental trends and understanding such trends will enable us to prepare for future events
	- Methodism => tendency to act in accordance with preestablished patterns
	- To be successful a planner must know when to follow established practice and went to strike out in a new direction
	- Plans must be translated into reality
	- Persistence often pace of
	- Taking the middle path between clinging stubbornly to a doomed plan and giving up a fundamentally good one at the first sign of difficulty is not easy
	- Are the premises for your actions correct?
	- We must be prepared to to acknowledge that a solution is not working
	- It is unwise however to abandon an established course of action too soon
	- We need a cohesive picture that lets us determine what is important and what is unimportant, what belongs together and what does not
	- Structural knowledge will allow us to find order in apparent chaos
	- 

** Setting Goals
 - To work toward a desirable state of affairs is a positive goal
 - to correct or prevent a deficient state of affairs is a negative goal
 - It is important to understand the link among goal criteria
 - We should always try to make general goals specific
 - Unless goals often contain multiple goals hidden within them
 - If we want to dispel the unclarity inherent in these complex concepts we must be deconstruct them
 - central and peripheral problems
 - Goals conflict with one another not by their very nature, but because the variables relating to them in the system are negatively linked
 - Ranking problems and delegating tasks are good strategies when we have more than one goal
 - Individual partial goals may be incompatible
 - Implicit goals are dangerous because they go unnoticed at the early stages of a planning process
 - The lack of knowledge is secondary
 - More important is that no one took the trouble to acquire the necessary knowledge
 - When we are working on a given problem we focus on that problem alone and not on problems that don't exist
 - The mistake is less not knowing then not wanting to know
 - Complex concept comprising many different components and their relationships to one another
 - Complex concept comprising many different components and their relationships to one another
 - Giving far too much attention to relatively unimportant problems and either over looking the truly important ones or failing to assess them properly
 - irrelevant criteria -
	 - the obviousness of a problem 
	 - our competence to solve it
 - If we act on the basis of a more or less randomly generated list of complaints we necessarily remain captives of the present moment
 - Human beings are constituted that they often find challenges attractive
 - *Success cannot be too certain or too unlikely*
 - Setting priorities by the Criterion of obviousness is not good
 - Selecting problems on the basis of your competence is also not good
 - A goal that remains unclear one that is not broken down into to concrete partial goals runs the risk of taking on a life of its own
 - An interim goal may dislodge the primary goal
 - We think we can find security in things that seem absolute and that protect us from all contradiction
 - We are infatuated with neat means, methods and techniques
 - Goals degenerate because of the Desire for safety and a lack of confidence in one's own capabilities
 - Inadequate analysis leads first of all to uncertainty
 - Realising we are attacking the wrong problems only makes us more on certain
 - If we have no criteria based on the specification of our goals to help us set priorities
	 - we will choose the most obvious problems or
	 - the ones that we already know how to solve
 - Repair service behaviour is surely preferable to correct obvious ills than to do nothing at all
 - Pragmatic politics not driven by the lofty ideals but by the exigencies of the situation
 - Pragmatic politics not driven by the lofty ideals but by the exigencies of the situation
 - If we formulate goals in concrete terms we should; if we cannot then muddling through is better than inaction
 - Something that doesn't cost much is rally of much benefit
 - *If you want to derive great benefit we usually have to investe a lot*
 - Contradictory goals are the rule not the exception in complex situations
 - Unrecognised contradictory relations between partial goals lead to actions that inevitable replace one problem with another
 - The verbal integrations of incompatibles can over time produce changes in the meanings of words
 - Our understanding of prevailing conditions is inadequate
 - It is difficult for us to admit to ourselves that despite the best of intentions we have failed
 - When we must deal with problems in complex systems few things are as important as setting useful goals
 - When we do not make overly General or unclear goals specific we are likely to spend time unwisely on ineffective repair service behaviour
 - Ultimately to salve our self confidence we may find ourselves choosing projects for their obviousness or ease rather than for their importance

*** Requirements of Goal setting

*** General Goals and "Repair Service" behavior

*** Liberty, Equality and "Voluntary Conscription"

** Information and Models
 - We can't focus only on what is wrong and what we want to correct
 - Most of the time the systemic nature of the situations was ignored
 - All effort had gone toward treating a symptom and none toward solving the underlying problem
 - A system is a network of many variables in causal relationships to one another
 - Within a system a variable may have a causal relationship to itself
 - It is usually wise when correcting a deficiency to consider it within the context of its system
 - *We may also overlook the unpleasant side effects of our actions and do more harm than good in the long run*
 - Positive feedback tends to undermine the stability of a system
 - It is obviously greatly to our advantage to look at a deficiency not in isolation but embedded in its system
 - We need to know more than just the causal relationships between individual variables in a system
 - *Knowledge of the constituent elements of a system can also give us important insights into the structure of that system*
 - Thinking by analogy => rather primitive and obvious step
 - It is essential to understand the relationships between broad and narrow concepts, between the Abstract and the concrete
 - *False hypotheses are better than no hypotheses at all because they can ultimately lead us to correct knowledge*
 - There is No a Priori appropriate level of detail
 - We should select the level of detail needed to let us understand the interrelationships among our goal variables
 - Goal variable are the variables we want to influence
 - *An important method to acquire knowledge about the structure of a system is analogy*

*** Reality, Models and Information

*** Solving problems one at a time
  - A bundle of independent mini systems
	- Take into account the side effects and repercussions of certain measures
	- If we do not concern ourselves with the problems we do not have, we soon how them
	- most of us lack an overall view of the system and of the reciprocal interactions with in it
  - The reason we deal with partial problems in isolation is our preoccupation with the immediate goals
	- It is obviously better if we know how the individual variables in the system relate to one another
	- Reductive hypothesis - tying everything to one variable
	- People use many dodges to defend their pet hypothesis  against logical argument or the evidence of experience
	- Reductive hypothesis provide simplest explanations for what goes on in the world accounts not only for their popularity but also for their persistence
	- Unsurveyability ->  uncertainty ->  fear
	- In extreme cases we may devise elaborate and dogmatic defences to protect hypotheses that in no way reflect reality
	- We are infatuated with the hypothesis we propose because we assume they give us power over things
	- Every situation has to be considered afresh
	- Context should determine strategy
	- *The world of our ideas is usually not particularly colourful*
	- Our ideas are pale outlines
	- *A necessary generalization can easily evolve into overgeneralization*
	- As a rule we have no opportunity to test in advance whether a concept we have developed has stuck just the right degree
		of abstraction or is an overgeneralization
	- deconditionalized concept - concept removed from the context of conditions bearing on it
	- *The effectiveness of a measure almost always depends  on the context within which the measure is pursued.*
	- |right degree of abstraction ------------ abstraction spectrum ---------------- overgeneralization|
	- similarity matching - tendency to respond to similarities more than to differences

*** "It's the Environment" 

*** Prime Numbers and Tourist Traffic or Moltke and Forest Fires

*** The Pale Cast of Thought

** Time Sequences

*** Time and Space

*** Lilypads, Grains of Rice and AIDS

*** A Premature All Clear

*** Laymen and Experts

*** "Twenty-eight is a good number"

*** Predators and Prey

*** The Moths of Kuera

** Planning

*** Go Make Yourself a Plan

*** Rumpelstilskin

*** Learn by Making Mistakes? Not Necessarily!

** So Now what we do?
