* The Beginning of Infinity
Author: David Deutsch

Explanations that transform the world

** Introduction
- All progress has resulted from a single human activity, the quest for good explanations.
- Much progress is unbounded.
- Although progress has no necessary end, it does have a necessary beginning.
-
** The Reach of Explanations
- The universe is seething with violent activity.
- Explanations:- assertions about what is out there and how it behaves
- Learning from experience => choose between theories
- inductive inference => general from the peculiar
- Scientific explanations are about reality.
- For if one cannot derive predictions from experience, one certainly cannot derive explanations.
- Since inductivism is false, empiricism must be as well.
- The sens*e cannot be deceptive in themselves.
- What misleads us are only the false interpretations that we place on appearances.
- Justification !== Fallibilism
- Fallibilism is essential for the initiations of unlimited knowledge growth - the beginning of infinity.
- *All observations are theory-laden, and hence fallible, as all our theories are*.
- conjecture - theoretical interpretation
- *We perceive nothing as what it really is*.
- *There is nothing more deceptive than an obvious fact.*
- cimenti = trials by ordeal
- Appearances are not self-explanatory
- *Prediction is not and cannot be the purpose of science*.
- Explanation is a statement of the reality that accounts for the appearance.
- There is no such thing as a purely predictive, explanationless theory.
- *Knowledge that is both familiar and uncontroversial is background knowledge.*
- *Solving a problem means creating an explanation that does not have the conflict.*
- Conflicting ideas in a broader sense are the occasion for all rational thought and inquiry.
- Expectations are theories too.
- There are no contradictions in reality.
- *Every problem signals that our knowledge must be flawed or inadequate*.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- A good explanation makes it harder for you to fool yourself
- The better an explanation is, the more rigidly its reach is determined.
- Ideas were static for long periods
- We need explanations to survive
- Apperances are deceptive
- The real source of our theories is conjecture
- The real source of our knowlege is conjecture alternating with criticism
- We interpret our experiences through explanatory theories but true explanations are not obvious.


** Closer to Reality
   - A galaxy is a ming-boggling huge thing. For that matter, a star is a mind-bogglingly huge thing.
   - A human brain is a ming-bogglingly huge thing in terms of both its internal complexity and the reach of human ideas.
   - One can be misled easily and thoroughly.
   - Progress requires the application of ever more knowlege in advance of our observations.
   - The quest for good explanations corrects the errors.
   - Scientific truths consists of such correspondence between theories and physical reality.
   - rare and fragile configurations of matter
   - Our minds, through the methodological criterion conclude that a particular thing is real if and only if it figures in our best explanation of something.
   - *We observe nothing directly. All observations are theory-laden*
   - *The growth of knowledge consists of correcting misconceptions in our theories.*
   - People can apply creativity even to tasks that computers and other machines do it uncreatively.
   - *Science is not mindless toil for which rare moments of discovery are the compensation*
   - The toil can be creative and fun, just as the discovery of new explanations is.
   - Whenever we make an error, it is an error in the explanation of something.



** The Spark
 - Anthropocentric approach has never yielded  any good explanations beyond the realm of human affairs
 - Anthropocentrism - explanatory and geometrical
 - The universe does not even have a geometrical centre
 - Human beings and their wishes and actions are extremely insignificant in the universe at large
 - The patterns of stars and planets in our night sky have no significance for human affairs
 - Living things, including humans, all consist of the same ingredients as rocks and stars, obey the same laws
	 that they were not designed by anyone
 - *People are significant in the cosmic scheme of things*
 - *The Earth's biosphere is incapable of supporting human life*
 - Anthropocentric errors are examples of parochialism, but not all parochialism is anthropocentric.
 - Earth is tiny and ephemeral
 - rich conceptual framework
 - We are uncommon form of ordinary matter
 - Matter
	 - 80% => Dark matter(invisible, neither emit nor absorb light)
	 - 20% => Ordinary matter (glowing continuously)
 - The biosphere is not a great preserver of species
 - The biosphere only ever achieves stability by continually neglecting, harming, disabling and killing individuals.
 - Knowledge was transmitted from generation to generation not genetically but culturally.
 - *It was only human knowledge that made the planet even marginally habitable*
 - They didn't realize anything, because they did not know how to seek better explanations
 - We assumed far too easily that the world was fundamentally incomprehensible to them
 - Evolution did not waste our resources on detecting phenomena that were never relevant to our survival
 - Human attributes evolved under natural selection in an ancestral environment
 - *Technology progess has depended specifically on the creation of explanatory knowledge.*
 - The increasingly intimate connection between explaining the world and controlling it is not accident, but is
	 part of the deep structure of the world
 - *All regularities in nature have explanations*
 - People -> entities that can create explanatory knowledge
 - *Humans can create and apply new knowledge*
 - We are accustomed to thinking of the Earth as hospitable
 - Every cell is a chemical factory
 - The opportunities provided by the laws of nature for transforming resources are universal
 - human bodies - universal constructors
 - *The only uniquely significant thing about humans is our ability to create new explanations*
 - Moral knowledge -> knowledge about what to want and what to strive for
 - *Human reach is the same as the reach of explanatory knowledge itself*
 - The human mind seeks explanations and now that we know how to find them, we are not going to stop voluntarily
 - The laws of physics forbid the creation of energy from nothing
 - *Humans are universal constructors*
 - *An unproblematic state is a state without a creative thought*
 - unproblematic state = death
 - All the fundamental constants of nature can be measured here
 - Every fundamental law can be tested here
 - Every problem of finding or transforming resources can be no more than a transcient factor limiting the creation of knowledge in a given environment
 - Matter, energy and evidence are the only requirements that an environment needs to have in order to be a venue for open-ended knowledge creation
 - *There has never been an unproblematic time for humans* That applies as much to the future as to the past
 - *There can be no such thing as an ultimate explanation*
 - *Problems are inevitable*
 - *Problems are soluble*
 - Humans are capable of attaining a state of supposed perfection
 - *Every attainable state can be indefinitely improved*
 - Our values and our objectives can continue to improve indefinitely
 - Earth is inundated with matter, energy and evidence
 - In the universe at large, knowledge friendliness is the rule not the exception
 - The fundamental laws of nature are so uniform and evidence about them so ubiquitous
 - Knowledge is a significant phenomenon in the universe
 - Non-explanatory knowledge cannot be universal
 - Proxy => a physical variable which can be measured as a way of measuring another variable
 - *All scientific measurements involve a chain of proxies*
 - Human, people and knowledge are not only objectively significant. They are by far the most significant phenomenon in nature
 - *All knowledge creating systems correct errors*
 - Universality and reach are inherent in the laws of nature
 - People are universal constructors
 - *New explanations create new problems*
 - *Everything that is not forbidden by laws of nature is achievable, given the right knowledge*
 - 


** Creation


** The Reality of Abstractions


** The Jump to Universality


** Artificial Creativity


** A Window on Infinity


** Optimism


** A Dream of Socrates


** The Multiverse


** A Physicist's History of Bad Philosophy




** Choices


** Why are Flowers Beautiful?


** The Evolution of Culture


** The Evolution of Creativity


** Unsustainable


** The Beginning


