* The Lessons of History
Author: Will Durant

** Hesitations
 - History has no sense
 - Our knowledge of any past event is always incomplete, probably inaccurate, beclouded by ambivalent
	 evidence and biased historians and perhaps distored by our own patriotic or religious partisanships
 - A multitude of doubts assail our enterprise
 - *Most history is guessing and the rest is prejudice*
 - mutitudinous complexity
 - Historiography cannot be a science
 - *The present is the past rolled up for action and the past is the present unrolled for understanding*
 - Total perspective is an optical illusion
 - All formulas should be suspect
 - *The historian always oversimplifies and hastily selects a manageable minority of facts and faces out
	 of a crowd of souls and events show multitudinous complexity he can never quite embrace or comprehend*
 - We do not know the whole of man's history
 - *We must operate with partial knowledge and be provisionally content with probabilities*
 - *Man is a moment in astronomic time; a transient guest of the earth*

** History and the Earth
 - *Human history is a brief spot in space and its first lesson is modesty*
 - troublesome duplexity
 - *Man's ingenuity often overcomes geological handicaps*
 - Geography is the matrix of history, it's nourishing mother and disciplining home
 - The influence of geographic factors diminishes as technology grows
 - *Man makes civilization*

** Biology and History
 - We belong to this perilous minority on this impartial planet
 - The laws of biology are the fundamental lessons of history
 - History is a fragment of biology
 - The life of man is a portion of the vicissitudes of organisms on land and sea.
 - Inequality is not only natural and inborn, it grows with the complexity of civilization
 - Freedom and equality are sworn and everlasting enemies and when one prevails the other dies
 - Utopias of equality are biologically doomed
 - Leave men free and their natural inequalities will multiply alomost geometrically
 - Nature has no use for organisms, variations or groups that cannot produce abundantly
 - Nature has a passion for quantity as prerequisite to the selection of quality
 - The equilibrium of production and reproduction
 - Ideally parentage should be a privilege of health, not a by-product of sexual agitation
 - Much of what we call intelligence is the result of individual eduction, opportunity and experience
 - Biologically, physical vitality at birth may be of greater value than intellectual pedigree
 - there is no humorist like history
 - The birth rate like war may determine the fate of theologies

** Race and History
 - History is color-blind and can develop a civilization under almost any skin
 - Climatic and geological conditions frustrated them
 - the role of race in history is rather preliminary  than creative
 - Circumstances geographical, economic and political create a culture and the culture creates a human type
 - Civilization is a co-operative product
 - 3 biological lessons of history:
	 - Life is competition
	 - Life is selection
	 - Life must breed
 - It is not the race that makes the civilization, it is the civilization that makes the people
 - In the long run such differences of tradition or type yield to the influence of the environment

** Character and History
 - Society is founded not on the ideals but on the nature of man
 - The constitution of man rewrites the constitution of states
 - Human nature is the fundamental tendencies and nature of mankind
 - most basic tendencies -> instincts
 - Known history shows little alteration in the conduct of mankind
 - *Means and instrumentalities change; ends and motives remain the same*
 - History in the large is the conflict of minorities
 - Evolution in man during recored time has been social rather than biological
 - Social evolution is an interplay of custom with origination
 - Development in the higher organisms require a capacity for experiment and innovation
 - *The imitative majority follows the innovative majority*
 - effects of numberless causes and causes of endless effects
 - Sex is a river of fire that must be banked and cooled by a 100 restraints if it is not
	 to consume in chaos both the individual and the group
 - Intellect is therefore a vital force in history, but it can also be a dissolvent and destructive power
 - The conservative who resists change is as valuable as the radical who proposes it
 - the conservative => resists change
 - the radical => proposes change
 - New ideas should be heard
 - New ideas should be compelled ot go through the mill of objection, opposition and contumely
 - Innovations must survive the trial heat before being allowed to enter the human race
 - creative tensile strenght
 - stimulated development


** Morals and History
 - Morals => the rules by which a society exhorts its members and associations to behaviour consistent with its order,
	 security and growth
 - Laws => the rules by which a society seeks to compel
 - Little knowledge of history => the variability of moral codes
 - Moral codes are negligible because they differ in time and place and sometimes contradict each other
 - Larger knowledge => the universality of moral codes and their necessity
 - economic history:
	 - hunting
	 - agriculture
	 - industry
 - *Insecurity is the mother of greed*
 - Moral codes differ because they adjust themselves to historical and environmental conditions
 - *Probably every vice was once a virtue*
 - *Man's sins may be the relic of his rise rather than the stigmata of his fall*
 - The new regime demanded new virtues and changed some old virtues into vices
 - The city offered every discouragement to marriage, but it provided every stimulus
	 and facility for sex
 - Women were emancipated
 - History offers some consolidation by reminding us that sin has flourished in every age
 - the immortality of our stage differs in kind rather than degree
 - Man has never reconciled himself to the 10 commandments
 - *History as usually written is quite different from history as ususally lived.*
 - *The Historian records the exceptional because it is interesting, because it is exceptional*
 - The freedom of the past varies with the security of the whole
 - History assures us that civilization decay quite leisurely
 - Meanwhile much of our moral freedom is good
 - It is pleasant to be relieved of the theological terrors
	 

** Religion and History
 - Religion has conferred meaning and dignity upon the lowliest existence
 - The natural inequality of men dooms many of us to poverty or defeat
 - *Heaven and utopia are buckets in a well; when one goes down the other goes up*
 - When religion declines, communism grows;
 - Religion does not seem at first to have had any connection with morals
 - *It was fear that first made the gods*
 - Religion became the propitiatory worship of these forces
 - Immortality flourished even in ages of religious domination
 - Morality should stand above power
 - The majestic dream broke under the attacks of nationalism, skepticism and human frailty
 - *Men often proved biased, venal and extortionate*
 - The Church played only a modest part in the outstanding advance of modern morality - the abolition of slavery
 - The growing awareness of man's minuscule place in the cosmos has furthered the impairment of religious belief
 - the ecclesiastical recognition
 - *Nature and history do not agree with our conceptions of good and bad*
 - *Science is the religion of modern emancipated man*
 - The Earth had become a mere suburb in the world
 - The awesome triumphs of scientific technology promising man omnipotence and destruction and challenging the divine
	 command of the skies
 - The idea of hell disappeared from educated thought, even from pulpit homilies
 - Laws which where once presented as the decrees of a god-given thing are now frankly confused commands of fallible men
 - One lesson of history is that religion has many lives and habit of resurrection
 - Puritanism and paganism alternate in mutual reaction in history
 - Puritanism => the repression of the senses and desire
 - Paganism => the expression of the senses and desire
 - *As long as there is poverty, there will be gods*
 - A natural ethic is too weak to withstand the savagery that lurks under civilization and
	 emerges in our dreams
	 



** Economics and History
 - History is economics in action
 - Unquestionably the economic interpretations illuminates much history
 - The subtle Greeks know to cover naked economic truth with the fig leaf of a phrase
 - The generals could write a military interpretation of history
 - The discovery of America was a result of the failure of the crusades
 - Civilization is a parasite on a man with the hoe
 - *Every economic system must sooner or later rely upon some form of profit motive to
	 stir individuals and groups to productivity*
 - *History is inflationary*
 - Money is the last thing a wise man will hoard
 - Normally and generally men are judged by their ability to produce
 - In war men are ranked according to their ability to destroy
 - The concentration of wealth is a natural result of this concentration of ability and regularly recurs in history
 - *The gap between the wealthiest and the poorest is no greather than at any time*
 - The concentration of wealth is natural and inevitable and is periodically alleviated by
	 violent or peaceful redistribution
 - *All economic history is the slow heartbeat of social organism*
 - The men who can manage the men who can manage only things, and the men who can manage money manage all.
 - substitutes:
	 - slavery
	 - police supervision
	 - ideological enthusiasm
 - substitutes like slavery, police supervision and ideological enthusiasm are too unproductive, expensive and transient
 - Economic history - a vast systole an diastole of concentrating wealth and compulsive redistribution

** Socialism and History
 - The Struggle of socialism against capitalism is part of the historic rhythm in the concentration and dispersion of wealth
 - In free enterprise, the spur of competition, the zeal and zest of ownershipt arouse the productiveness and inventiveness of men
 - Nearly every economic activity sooner or later finds its niche and reward in the shuffle of talents and the natural selection of skills
 - Competition compels the capitalist to exhaustive labor, and its products to every rising excellence
 - moral disintegration spread
 - Other factors equal, internal liberty varies inversely as external danger
 - *Human corrupitibility and incompetence make governmental control of industry impracticable*
 - a choice between private plunder or public graft
 - The fear of capitalism has compelled socialism to widen freedom
 - The fear of socialism has compelled capitalism to increase equality
	 

** Government and History
 - Men love freedom
 - The freedom of individuals in society requires some regulation of conduct
 - The first conditions of freedom is its limitation
 - The prime task of government is to establish order
 - Organized central force is the sole alternative to incalculable and disruptive force in private hands
 - *Power naturally converges to a center*
 - *Power is ineffective when divided, distributed and spread*
 - Monarchy seems to be the most natural kind of government
 - *Democracies have been hectic interludes*
 - Monarchy was adoptive
 - prevalence and duration in history
 - When monarchy is of hereditary, it is likely to be more prolific of stupidity, nepotism,
	 irresponsibility and extravagance than of nobility or statesmanship
 - Aristocracy is a nursery of statesmanship
 - It is unnatural for a majority to rule
 - A majority can seldom be organized for united and specific action and a minority can
 - Aristocracy is a repository of vehicle of culture, manners, standards and tastes and serves thereby as a stabilizing barrier
 - the consuming toil is usually the price of genius
 - The services of aristocracy oppressed the people with selfish and myopic exploitation
 - IN some cases outworn and inflexible institutions seem to require violent overthrow
 - *The sanity of individual lies in the continuity of his memories*
 - *The sanity of a group lies in the continuity of its traditions*
 - The only real emancipation is individual
 - Wealth is an order and procedure of production and exchange rather than an accumulation of goods
 - Violent revolutions do no so much redistribute wealth as destory it.
 - *The only real revolution is in the enlightenment of the mind and the improvement of character.*
 - The only real revolutionists are philosophers and saints
 - There was no length to which violence did not go
 - *The excessive increase of anything causes a reaction in the opposite direction*
 - Dictatorship naturally arises out of democracy
 - pleonexia => an appetite for more and more
 - The most aggravated form of tyranny and slavery out of the most extreme form of liberty
 - Democracy is the most difficult of all forms of government
 - The Platonic wheel had come full turn
 - *War becomes more consuming and the individual is helpless to understand its causes or to escape its effects*
 - Every advance in the complexity of the economy puts an added premium upon superior ability, and intensifies the
	 concentration of wealth, responsibility and power
 - *We forget to make ourselves intelligent when we made ourselves sovereign*
 - Education has spread, but intelligence is perpetually retarded by the fertility of the simple
 - Ignorance is not only enthroned, for it lends itself to manipulation by the forces that mold public opnion
 - Democracy has done less harm and more good
 - Democracy gave to human existence a zest and camaraderie that outweighed its pitfalls and defects
 - The freedoms of democracy may one by one succumb to the discipline of arms and strife
 - Democracy gave to thought and science and enterprise the freedom essential to their operation and growth
 - Democracy is today sounder than ever before
 - Democracy broke down the walls of privilege and class and in each generation it raised up ability from every rank and place
 - A martial government under whatever charming phrases will engulf the democratic world
 - Democracy has dictated itself resolutely to the spread and lengthening of education and to the maintenance of public health
 - If equality of educational opportunity can be established, democracy will be real and justified.
 - Though men cannot be equal, their access to education and opportunity can be made more nearly equal
 - A right is not a gift of God or nature but a privilege which is good for the group that the individual should have
 - The rights of man are not rights to office and power, but the rights of entry into every avenue that may nourish and test
	 a man's fitness for office and power


** History and War
 - *War is one of the constants of history, and has not diminished with civilization or democracy*
 - War is at present the ultimate form of competition and natural selection in the human species
 - War or competition is the father of all things, the potent source of ideas, inventions, institutions and states
 - Peace is an unstable equilibrium, which can be preserved only by acknowledged supremacy or equal power
 - The state has our instincts without our restraints
 - Pride gives added vigor in the competitions of life in the individual
 - One war can now destroy the labor of centuries in building cities, creating art and developing habits of civilization
 - In apologetic consolation, war now promotes science and technology.
 - In the military interpretation of history war is the final arbiter
 - In the military interpretation of history, war is accepted natural and necessary by all but cowards and simpletons
 - A long peace may fatally weaken the martial muscles of a nation
 - Magnanimty in politics is not seldom the truest wisdom
 - *A great empire and little minds go ill together*
 - Cultural exchanges will promote mutual appreciation and understanding
 - *Some conflicts are too fundamental to be resolved by negotiation*
 - the grateful memory of mankind
 - *A world order will not come by a gentleman's agreement*
 - Such interludes of widespread peace are unnatural and exceptional
 - Man is a competitive animal
 - Natural selection now operates on an international plane
 - Perhaps we are now restlessly moving toward that higher plateau of competition

** Growth and Decay
 - Civilization is social order promoting cultural creation
 - History is littered with ruins of civilizations
 - Death is the destiny of all
 - In a developed and complex civilization individuals are more differentiated and unique than in a primitive society
 - Custom recedes; reasoning spreads
 - Many situations contain nover circumstances requiring modifications of instinctive response
 - a continuity of production and exchange
 - There is no certainty that the future will repeat the past
 - Every year is an adventure
 - History repeats itself but only in the outline and in the large
 - Human nature changes with geological leisureliness
 - History repeats itself in the large
 - *The excitement of innovation will be forgotten in the unconcern of time*
 - Man is equipped to respond in stereotyped ways to frequently occuring situations and stimuli like hunger, danger and sex
 - age of philosophy => age of criticism
 - Civilizations begin, flourish, decline and disappear
 - Economic prevision and provision constituted another basis for civilization
 - The moral code looses aura and force as its human origin is revealed, and as divine surveillance and sanctions are removed
 - genius => creative individuals with clarity of mind and energy of will
 - intelligence => capable of effective responses to new situations
 - An age of weary skepticism and epicureanism followed the triump of rationalism over mythology
 - The group or a civilization declines through the failure  of its political or intellectual leaders to meet the
	 challenges of change
 - inequality grows in an expanding economy
 - The challenges may come from a dozen sources, and may by repetition or combination rise to a destructive intensity
 - In antiquity and modernity alike, analytical thought dissolved the religion that had buttressed the moral code
 - Religion had buttressed the moral code
 - As education spreads, theologies lose credence
 - *Life has no inherent claim to eternity, whether in individual or in states*
 - If death comes in due time, it is forgivable and useful
 - The mature mind will take no offense from the  coming of death
 - nations die
 - Basic problems:
	 - theological
	 - political
	 - economical
	 - moral
 - communication and transport => nourishing placenta
 - the selective survival of creative minds is the most real and beneficient of immortalities
 - *Resilient man picks up his tools and his arts and moves on taking his memories with him*

** Is Progress Real?
 - *There is no substantial change in man's nature during historic times*
 - *We repeatedly enlarge our instrumentalities without improving our purposes*
 - The replacement of chaos with order is the essence of art and civilization
 - History is so indifferently rich that a case for almost any conclusion from it can be made by a selection of instances
 - We merely transfered intolerance from religions to national, ideological or racial hostilities
 - There is a stealthy pressure in rejecting mankind or the universe as unworthy of our own approval
 - Progress is the increasing control of the environment by life
 - *We should not  demand of progress that it should be continuous or universal*
 - Under the complex strains of city life we sometimes take imaginative refuge in the supposed simplicity of pre-civilized ways
 - Life should take fresh forms
 - *Education is not the painful accumulation of facts, dates and reigns*
 - Education is not merely the necessary preparation of the individual to earn his keep in the world
 - The heritage rises and man rises in proportion as he receives it
 - *History is the creation and recording of heritage*
 - Progress is heritage's increasing abundance, preservation, transmission and use
 - Let it be our pride that we ourselves may put meaning into our lives and sometimes
	 a significance that transcends death.
