* The Beginning of Infinity
Author: David Deutsch

Explanations that transform the world

** Introduction
- All progress has resulted from a single human activity, the quest for good explanations.
- Much progress is unbounded.
- Although progress has no necessary end, it does have a necessary beginning.
-
** The Reach of Explanations
- The universe is seething with violent activity.
- Explanations:- assertions about what is out there and how it behaves
- Learning from experience => choose between theories
- inductive inference => general from the peculiar
- Scientific explanations are about reality.
- For if one cannot derive predictions from experience, one certainly cannot derive explanations.
- Since inductivism is false, empiricism must be as well.
- The sens*e cannot be deceptive in themselves.
- What misleads us are only the false interpretations that we place on appearances.
- Justification !== Fallibilism
- Fallibilism is essential for the initiations of unlimited knowledge growth - the beginning of infinity.
- *All observations are theory-laden, and hence fallible, as all our theories are*.
- conjecture - theoretical interpretation
- *We perceive nothing as what it really is*.
- *There is nothing more deceptive than an obvious fact.*
- cimenti = trials by ordeal
- Appearances are not self-explanatory
- *Prediction is not and cannot be the purpose of science*.
- Explanation is a statement of the reality that accounts for the appearance.
- There is no such thing as a purely predictive, explanationless theory.
- *Knowledge that is both familiar and uncontroversial is background knowledge.*
- *Solving a problem means creating an explanation that does not have the conflict.*
- Conflicting ideas in a broader sense are the occasion for all rational thought and inquiry.
- Expectations are theories too.
- There are no contradictions in reality.
- *Every problem signals that our knowledge must be flawed or inadequate*.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- A good explanation makes it harder for you to fool yourself
- The better an explanation is, the more rigidly its reach is determined.
- Ideas were static for long periods
- We need explanations to survive
- Apperances are deceptive
- The real source of our theories is conjecture
- The real source of our knowlege is conjecture alternating with criticism
- We interpret our experiences through explanatory theories but true explanations are not obvious.


** Closer to Reality
   - A galaxy is a ming-boggling huge thing. For that matter, a star is a mind-bogglingly huge thing.
   - A human brain is a ming-bogglingly huge thing in terms of both its internal complexity and the reach of human ideas.
   - One can be misled easily and thoroughly.
   - Progress requires the application of ever more knowlege in advance of our observations.
   - The quest for good explanations corrects the errors.
   - Scientific truths consists of such correspondence between theories and physical reality.
   - rare and fragile configurations of matter
   - Our minds, through the methodological criterion conclude that a particular thing is real if and only if it figures in our best explanation of something.
   - *We observe nothing directly. All observations are theory-laden*
   - *The growth of knowledge consists of correcting misconceptions in our theories.*
   - People can apply creativity even to tasks that computers and other machines do it uncreatively.
   - *Science is not mindless toil for which rare moments of discovery are the compensation*
   - The toil can be creative and fun, just as the discovery of new explanations is.
   - Whenever we make an error, it is an error in the explanation of something.



** The Spark
 - Anthropocentric approach has never yielded  any good explanations beyond the realm of human affairs
 - Anthropocentrism - explanatory and geometrical
 - The universe does not even have a geometrical centre
 - Human beings and their wishes and actions are extremely insignificant in the universe at large
 - The patterns of stars and planets in our night sky have no significance for human affairs
 - Living things, including humans, all consist of the same ingredients as rocks and stars, obey the same laws
	 that they were not designed by anyone
 - *People are significant in the cosmic scheme of things*
 - *The Earth's biosphere is incapable of supporting human life*
 - Anthropocentric errors are examples of parochialism, but not all parochialism is anthropocentric.
 - Earth is tiny and ephemeral
 - rich conceptual framework
 - We are uncommon form of ordinary matter
 - Matter
	 - 80% => Dark matter(invisible, neither emit nor absorb light)
	 - 20% => Ordinary matter (glowing continuously)
 - The biosphere is not a great preserver of species
 - The biosphere only ever achieves stability by continually neglecting, harming, disabling and killing individuals.
 - Knowledge was transmitted from generation to generation not genetically but culturally.
 - *It was only human knowledge that made the planet even marginally habitable*
 - They didn't realize anything, because they did not know how to seek better explanations
 - We assumed far too easily that the world was fundamentally incomprehensible to them
 - Evolution did not waste our resources on detecting phenomena that were never relevant to our survival
 - Human attributes evolved under natural selection in an ancestral environment
 - *Technology progess has depended specifically on the creation of explanatory knowledge.*
 - The increasingly intimate connection between explaining the world and controlling it is not accident, but is
	 part of the deep structure of the world
 - *All regularities in nature have explanations*
 - People -> entities that can create explanatory knowledge
 - *Humans can create and apply new knowledge*
 - We are accustomed to thinking of the Earth as hospitable
 - Every cell is a chemical factory
 - The opportunities provided by the laws of nature for transforming resources are universal
 - human bodies - universal constructors
 - *The only uniquely significant thing about humans is our ability to create new explanations*
 - Moral knowledge -> knowledge about what to want and what to strive for
 - *Human reach is the same as the reach of explanatory knowledge itself*
 - The human mind seeks explanations and now that we know how to find them, we are not going to stop voluntarily
 - The laws of physics forbid the creation of energy from nothing
 - *Humans are universal constructors*
 - *An unproblematic state is a state without a creative thought*
 - unproblematic state = death
 - All the fundamental constants of nature can be measured here
 - Every fundamental law can be tested here
 - Every problem of finding or transforming resources can be no more than a transcient factor limiting the creation of knowledge in a given environment
 - Matter, energy and evidence are the only requirements that an environment needs to have in order to be a venue for open-ended knowledge creation
 - *There has never been an unproblematic time for humans* That applies as much to the future as to the past
 - *There can be no such thing as an ultimate explanation*
 - *Problems are inevitable*
 - *Problems are soluble*
 - Humans are capable of attaining a state of supposed perfection
 - *Every attainable state can be indefinitely improved*
 - Our values and our objectives can continue to improve indefinitely
 - Earth is inundated with matter, energy and evidence
 - In the universe at large, knowledge friendliness is the rule not the exception
 - The fundamental laws of nature are so uniform and evidence about them so ubiquitous
 - Knowledge is a significant phenomenon in the universe
 - Non-explanatory knowledge cannot be universal
 - Proxy => a physical variable which can be measured as a way of measuring another variable
 - *All scientific measurements involve a chain of proxies*
 - Human, people and knowledge are not only objectively significant. They are by far the most significant phenomenon in nature
 - *All knowledge creating systems correct errors*
 - Universality and reach are inherent in the laws of nature
 - People are universal constructors
 - *New explanations create new problems*
 - *Everything that is not forbidden by laws of nature is achievable, given the right knowledge*
 - 


** Creation
 - Good adaptations are distinguished by being hard to vary while still fulfilling their functions.
 - Knowledge is very unlikely to come into existence other than through the error correcting processes of evolution or thought.
 - Knowledge:
	 - Biological
	 - Explanatory
 - Some historic misconceptions about biological evolution have counterparts in misconceptions about human knowledge.
 - Who designed the designer?
 - *A good design is hard to vary*
 - Knowledge must be first conjectured and then tested
 - Evolution optimises neither the good of the species nor the individual.
 - Not all evolution constitutes progress and no(genetic) evolution optimizes progress
 - Organisms are the slaves, tools that genes use to achieve their purpose of spreading themselves throughout the population
 - Nearly all long lasting ideas are memes
 - Ideas can be replicators too
 - Memes => ideas that are replicators
 - No human knowledge is entirely non-explanatory
 - People often try to improve explanations even when they have received them accurately
 - People rarely express ideas in exactly the same words in which they heard them
 - *Good explanations are hard to vary*
 - The existence of an unsolved problem in physics is no more evidence for a supernatural explanation
 - Prediction changes radically if there are several constants to explain
 - There are infinitely many logically possible laws of physics
 - Almost random states are by far the most numerous
 - Specific explanation in terms of specific laws of nature is needed
 - An idea so simple, that we will all say to each other, how could it have been otherwise
 - Scientific discovery is profoundly unpredictable, despite the fact that it is determined by the laws of physics
 - Genes and ideas are both replicators
 - Knowledge and adaptations are both hard to vary
 - *Human knowledge can be explanatory and can have great reach*
 - The problem has been no that the world is so complex that we cannot understand why it looks as it does,
	 but it is that it is so simple that we cannot yet understand it.
 - Adaptations are never explanatory  and rarely have much reach beyond the situations in which they evolved.

** The Reality of Abstractions
 - *Guiding Principle* - Always reject bad explanations in favor of good ones
 - Emergent phenomena are essential to the explicability of the world
 - All knowledge creation depends on and physically consists of emergent phenomena.
 - *The explanation in one field affects our understanding of other fields*
 - We can let our theories die in our place
 - Abstractions are essential to a fuller explanation
 - myopic to the point of silliness
 - *Empiricism has multiple fatal flaws*
 - Criticism is correspondingly effective
 - The growth of knowledge does not consisting of finding ways to justify one's beliefs. It consists of finding good explanations
 - *The truth has structural unity and logical consistency*
 - Factual knowledge can be useful in criticising moral explanations
 - *There is an objective difference between right and wrong*
 - There is such a thing as objective beauty
 - There is no avoiding what-to-do-next problems
 - *Progress depends on explanation*
 - Trying to conceive of the world as merely a sequence of events with unexplained regularities would entail giving up on progress
 - Explanations do not form a hierarchy
 - Our knowledge of abstractions comes from the fact that our best explanations invoke them


** The Jump to Universality
 - Innovation is unpredictable
 - The largest benefits of any universality come from its begin useful for further innovation
 - *Progress is both desireable and attainable*
 - Universality is both desireable and attainable
 - Universality was being sought deliberately as a desireable feature in its own right
 - because of the usual lack of interest in universality
 - Physical objects are unlike each other and dominated by different laws of physics can exhibit the same mathematical relationships
 - tragic might-have-beens of history
 - The history of electronic technology since 2nd world war was dominated by miniaturization
 - *Error-correction is the beginning of infinity*
 - It is in the very nature of analogue computation that every value could be correct
 - Analogue computation can never be universal
 - All universal computers are digital and all use error-correction with the same basic logic
 - In reality, information that cannot be reliably retrieved is not really being stored.
 - The limitation that the information being processed must be digital does not detract from the universality of digital computers or of the laws of physics
 - It is just a matter of approximating continuously variable quantities by a sufficiently fine grid of discrete ones
 - The laws of physics are such that the behavior of any physical object can be simulated with any desired accuracy by a universal computer
 - Reach always has an explanation
 - People are universal explainers and universal constructors
 - *All knowledge growth is by incremental improvement*
 - Universal computers cannot really be universal unless there are people present to prove energy and maintenance indefinitely
 - Even life on Earth will eventually be extinguished unless people decide otherwise
 - Only people can rely on themselves into the unbounded future
 - *The jump to universality*: The tendency of gradually improving systems to undergo a sudden large increase in functionality becoming universal in some domain
 - Error-correction is essential in the process of potentially unlimited length
 - *The jump to universality only ever happens in digital systems*


** Artificial Creativity
 - quale - the subjective aspect of sensations
 - Qualia are currently neither describable nor predictable
 - a constellation of attributes
 - If you can't program it, you haven't understood it.
 - It is very rare for practical solutions to fundamental problems to be discovered without any explanation of why they work
 - Becoming better at pretending to think is not the same as coming closer to being able to think
 - The theory of evolution does not have to account for why every specific mutation succeeded or failed in the history of a given adaptation
 - AI abilities must have some sort of universality
 - Every AI is a person: a general purpose explainer
 - The ability to imitate a human imperfectly or in specialized functions is not a form of universality
 - stimuli = external circumstances; responses = observed behaviors
 - *Progress requires alternating inspiration and perspiration phases*
 - Biological evolution often reaches local maxima of fitness
 - jump to universality
 - We do not know why the DNA code has enough reach
 - *We do not understand how creativity works*
 - constellation of associated attributes
 - We do not understand the nature of the universality of the DNA replication system


** A Window on Infinity
 - Argument from personal incredulity => a preference for parochial misconceptions over universal truths
 - *Finitism is inherently anthropocentric*
 - Many facts about finite things are just as counter-intuitive
 - Law of the excluded middle: For every meaningful proposition, either it or its negation is true
 - Space was usually regarded as a continuum
 - *Even a finite line is composed of infinitely many points*
 - Beginning of infinity => a condition where progress in the future will be unbounded
 - Beginning of infinity => a condition where an infinite amount of progress will be made
 - Finitism regards parochialism as a virtue of a theory rather than a vice.
 - All abstract theorizing is theory laden too
 - Finite is parochial
 - *The best explanation of anything eventually involves universality and infinity*
 - The reach of explanations cannot be limited by fiat.
 - intuitions about infinity are often illogical
 - Not all infinities are equal
 - Larger infinities are called uncountable
 - Countable infinity => an infinity that is small enough to be placed in one-to-one correspondence with natural numbers
 - *Infinity is not magic; it has logical rules*
 - No theory explains everything
 - The beginning of infinity is one of the attributes of the unbounded growth of knowledge
 - We are only just scratching the surface and shall never be doing anything else
 - probable or improbable, rare or common, typical or untypical attributes have literally no meaning in regard to
	 comparing infinite sets of natural numbers
 - *Anthropic reasoning by itself cannot make any predictions*
 - Anthropic reasoning can't explain the fine-tuning of the constants of physics
 - We only every experience symbols
 - Quantum theory describes a multiverse and provides a measure for universes
 - Something is definitely finite if it could in principle be encompassed by a human experience
 - Physics deal in distances, not numbers of points
 - *Only the laws of physics determine what is finite in nature*
 - The laws of physics are consistent
 - The laws of physics determine the distinction not only between rare and common, probable and improbable,
	 fine-tuned or not, but even finite and infinite
 - Almost all mathematical truths have no proofs
 - Almost all mathematical truths are unprovable truths
 - Almost all mathematical statements are undecidable. Each of them is either true or false
 - The laws of physics provide us with only a narrow window through which we can look out on the world of abstractions
 - Abstracts exist objectively
 - The laws of physics support computational universality
 - Only the laws of physics that determine which abstract entities and relationships are modelled by physical objects
 - Infinite makes sense mathematically, so why not infinite proofs?
 - *Mathematics seek not random truths, but good explanations*
 - Real proof is independent of physics
 - Proof theory => computer science
 - There is no such thing as abstractly proving something
 - There is no such thing as abstractly knowing something
 - Mathematical truth is absolutely necessary and transcendent
 - All knowledge is generated by physical processes and its scope and limitations are conditioned by the laws of nature
 - The whole motivation for seeking a perfectly secure foundation for mathematics was mistaken.
 - The object of mathematics is to understand - to explain - abstract entitites
 - *Proof is a primary means of ruling out false explanations*
 - The whole point of universality is lost, if one conceives of computation as beign somehow prior to the physical world generating its laws
 - One does not understand a mathematical proposition by merely proving it true
 - *Problems are conflict between ideas*
 - Most mathematical questions that exist abstractly are uninteresting
 - Mathematical knowledge does not consist only of proofs
 - *We cannot create knowledge other than the fallible method of conjecture and criticism*
 - Fallibilism tells us that we can be mistaken about what is interesting
 - Errors are inevitable
 - We cannot prophesy; we cannot predict the content of ideas yet to be created or their effects
 - The problems are soluble does not mean that we already know their solutions or can generate them to order
 - *Only error correcting processes can succeed or continue for long*
 - *There are truths about the physical world that we shall never know*
 - limitations:
	 - directly imposed by the universal laws of physics
	 - epistemology
 - The unpredictability of the content of our future knowledge is a necessary condition for the unlimited growth of that knowledge
 - We can understand infinity through the infinite reach of some explanations


** Optimism
 - The possibilities that lie in the future are infinite
 - It is  our duty to remain optimists
 - All of us contribute to future by everything we do
 - *We are all responsible for what the future holds in store*
 - openness of the future
 - It is our duty not to prophesy evil, but , rather to fight for a better world
 - *Our own future will be shaped by knowledge that we do not yet have*
 - We cannot even predict most of the problems that we shall encounter or most of the opportunities to solve them
 - *Observations are theory laden*
 - Blind optimism is a stance towards the future
 - Both the original optimism and original pessimism are close to pure pessimism
 - Moods do not necessitate any particular stance about the future
 - Blind pessimism - precautionary principle
 - A single catastrophic consequence of an otherwise beneficial innovation could put an end to human progress for ever
 - *The good can be unlimited*
 - The harm that can flow form any innovation that does not destroy the growth of knowledge is always finite
 - There is only one way of making progress: conjecture and criticism
 - We cannot be sure that our present knowledge is not riddled with dangerous gaps and misconceptions
 - Blind optimism and blind pessimism are very similar at the level of explanation
 - We do not yet know what we have not yet discovered
 - the deeper explanation is lack of knowledge
 - Quite generally, the distinction between a natural disaster and one brought about by ignorance is parochial
 - *Civilizations starved because of lack of knowledge*
 - We live in an era of unprecedented safety
 - All sources of knowledge are liable to lead us into error at times
 - We have such a chance becausewe are able to solve problems
 - We shall always be faced with the problem of how to plan for an unknowable future
 - How can we hope to detect and eliminate error?
 - No such ideal sources of knowledge exists
 - We should choose between conjectures not on the basis of their origin, but according to how good they are as explanations: how hard to vary
 - *Science is what we have learned about how to keep from fooling ourselves*
 - Induction, instrumentalism and even Lamarckism all make the same mistake: they expect explanationless progress
 - One should not expect knowledge to be created by fiat with few errors
 - Knowledge should be created by a process of variation and selection that is making a continual stream of errors and correcting them.
 - People are different and have unique ideas
 - Problems are inevitable and progress consists of solving them.
 - *Optimism is a way of explaining failure, not prophesizing success
 - Whenever we try to improve things and fail, it is always becuase we did not know enough, in time.
 - It is only a matter of knowing how.
 - Progress cannot take place at all, unless someone is open to and prepares for, those inconceivable possibilities
 - Optimization implies all the other necessary conditions for knowledge to grow
 - We have a duty to be optimistic - in general and about civilization in particular
 - We want to engage with projects that will involve creating new knowledge
 - An optimist expects the creation of knowledge to constitute  progress - including its unforeseeable consequences
 - Pessimism has been endemic in almost every society throughout history
 - The end of pessimism is potentially a beginning of infinity
 - Democracy promotes wise action
 - Continual discussion is a necessary condition for discovering the right answer, which is in turn a necessary condition for progress
 - *Optimism is the theory that all failures are due to insufficient knowledge*
 - There are not fundamental limitations to the creation of knowledge
 - Progress towards is made by seeking good explanations
 - Problems are inevitable because our knowledge will always be infinitely far from complete
 - It is a mistake to confuse hard problems with problems unlikely to be solved
 - An optimistic civilization is open and not afraid to innovate and is based on traditions of criticism
 - Problems are soluble and each particular evil is a problem that can be solved
 - The institutions of optimistic civilization keep improving
 - The most important knowledge, the institutions of optimistic civilizations embody is knowledge of how to detect and eliminate errors


** A Dream of Socrates
 - openness to persuasion and defiance of bullies
 - Epistemology - knowledge about knowledge
 - It is not true that every just person knows the connection between reason, morality and the reluctance to defer to gods
 - *Objective knowledge is hard to come by but attainable*
 - Justified belief is sought by many people
 - Beliefs cannot be justified, except in relation to other beliefs and even then only fallibly
 - The quest for the justification of beliefs can lead only to an infinite regress, each step of which would itself be subject to error
 - Knowledge is a chimera
 - Justified belief is a chimera
 - Knowledge - justified belief
 - We often fail to see things that are there in reality
 - It is easy to be mistaken
 - We could be mistaken or misled in regard to what is right and wrong
 - Outside tricks or illusions affect only our senses and not our reason
 - In the course of time, through seeking, we may learn and know better
 - It is so hard to be systematically deceived on moral issues
 - Values:
   - open to suggestions
   - tolerant of dissent
   - critical of botth dissent and received opinion
 - *People who converge upon the truth converge upon each other*
 - Moral truths follows logically from epistemology
 - We seek improvement by constantly criticising and debating and trying to correct our ideas and behaviour
 - It's all easy to attribute universal truth to mere local appearances
 - Our very idea that improvement is possible implies that there must be errors and inadequacies in our current ideas
 - The perfect way of life involves few accomplishments and being wrong about most things
 - *We all are fallible and subject to misconceptions and errors in all our thinking*
 - We are fallible in all our thinking
 - There is literally no idea that we may safely hold immune from criticism
 - *Knowledge held immune from criticism can never be improved.*
 - Salvation would come about through persuasion, thought and explanation
 - *Always bear human fallibility in mind*
 - Some moral truths follow logically from epistemological considerations
 - All knowlege comes from persuasion
 - *The moral imperative not to destroy the means of correcting mistakes is the only moral imperative*
 - The quest for knowledge is striving to see beyond what is easy to see, to understand beyond what is easy to understand
 - Nothing is easy to see without prior knowledge
 - All knowledge of the world is hard to come by
 - Knowledge follows that we do not come by it through seeing
 - It does not flow into us through our senses
 - No need to trust the source if the argument itself is persuasive
 - All knowledge originates from the same source as dreams which is within ourselves
 - For all is but a woven web of guesses
 - *Guesswork is the origin of all knowledge*
 - What happens to an idea after it has been guessed is crucial
 - People do not always do what can work
 - We first guess what is there and then we our guesses against the input from our senses
 - all encompassing conjuring trick
 - Man is the paragon of animals
 - We weave stories of an outside world
 - We are not satisfied with merely weaving, nor with mere stories
 - We want true explanations
 - There is no upper bound to how much we can eventually understand and control and achieve
 - Once the experience is over, all that matters is what you learned from it.
 - improvement vs stasis
 - Genuine knowledge is impossible
 - Justified belief is impossible
 - We can come to know the true world beyond the illusory world of experience
 - The only true knowledge is that which comes from within
 - We can never know the reality outside because we see only fleeting, distorted shadows of it.
 - Epistemology seems a tremendously for-reaching and important subject
 - Things are going to be endlessly tinkered with and improved
 - We habitually underestimate the difficulty of communication
 - Misunderstandings are ubiquitous
 - Neither intelligence nor the intention to be accurate is any guarantee against them
 - *Objective knowledge though attainable, is hard to obtain*
 - Improvements are cumulative
 - The way to converge with each other is to converge upon the truth


** The Multiverse
 - The world is the whole of physical reality
 - Imagining inexplicable worlds can help us to understand the nature of explicability
 - According to quantum physics, the world is a much larger and more complicated object, a multiverse
 - The concept of fungibility is everywhere just beneath the conceptual surface
 - In quantum physics, elementary particles are configurational entities
 - Diversity within fungibility is a widespread phenomenon in the multiverse
 - *Imagination may baulk, reason does not*
 - There are no fundamentally random (indeterministic) variable
 - Fungibility is essential to the explanation of quantum randomness and most other quantum phenomena
 - It is fungibility and parallel universes that are responsible for a given phenomenon
 - Ideas originating in the other universe are at least as fallible as those in ours.
 - *Knowledge creation depends on error-correction*
 - Nothing would be left fungible after the wave of differentiation had passed.
 - *Changes don't happen instantaneously*
 - Knowledge can aim itself at a target, travel vast distances having scarcely any effect and then utterly transform the destination
 - Certain circumstances can explain other events, without being in any way involved in causing them.
 - If we are not careful, common sense makes false assumptions about the physical world.
 - Parochialism => People observe a phenonmenon but they are failing to understand it as part of a wider phenomenon most of which they do not observe
 - There is great order and regularity in that apparent chaos
 - All the universes, despite their differences obey the same laws of physics (including their initial conditions)
 - *The histories are nearly autonomous*
 - Entanglement information => Every object carries within it information about which instances of it could interact with which instances of other objects
 - Quantum interference phenomena constitute our main evidence of the existence of the multiverse and of what its laws are
 - decoherence => process of differential effects becoming infeasible
 - Heisenberg uncertainty principle => It follows from the laws of quantum physics, for any fungible collection of instances of a physical object
   some of their attributes must be diverse
 - quantum mechanical law of motion
 - diversity within fungibility
 - The uncertainty principle is deduced from the principles of quantum theory
 - A typical electron is an irreduceably multiverse object
 - The reality is an electron field throughout the whole of space and disturbances spread through this field
   as waves at the speed of light or below.
 - History == Geological stratum
 - There are regions of the multiverse that contain short-lived histories and others that do not even approximately contain histories
 - Within a history, using classical physics one can successfully predict some aspects of the future of that history from its past.
 - A great deal of fiction is therefore close to a fact somewhere in the multiverse
 - Quantum computers are limited by laws of physics that govern quantum interference
 - In classical physics, a tiny effect always means a tiny change in some measurable quantities
 - Quantum theory of gravity => quantum theory + general theory of relativity
 - Different times are a special case of different universes
 - *All fiction that does not violate the laws of physics is a fact*
 - The history approximation breaks down completely in interference phenomena
 - *We are channels of information flow*
 - Histories are channels of information flow
 - We sentient begins are extremely unusual channels, along which knowledge grows
 - *There are many more ways of being wrong than right*
 - All relatively autonomous objects within histories are all channels of information flow.
 - We are embedded in multiversal objects
 - *The growth of knowledge is a process of error correction*
 - We are at the top rank of significance in the great scheme of things
 - The Physical world is a multiverse and its strucutre is determined by how information flows in it.


** A Physicist's History of Bad Philosophy
 - Quantum theory does have universal reach.
 - I am an emergent, quasi-autonomous flow of information in the multiverse
 - Bad philosophy is philosophy that is not merely false, but actively prevents the growth of other knowledge
 - *Error is the normal state of our knowledge and is no disgrace*
 - Problems are inevitable, but they can be solved by imaginative, critical thought that seeks good explanations
 - stand outside the jurisdiction of normal criticism
 - Nothing is ever derived from observation
 - Spacetime really exists even though it cannot be directly observed.
 - *Creating a good explanation is hard*
 - The method of seeking good explanations creates an engagement with reality
 - *Explanationless prediction is actually impossible*
 - Behaviorism is instrumentalism applied in psychology
 - *All scientific measurements use chains of proxies*
 - testable expalantory theory of what happiness is
 - statistical correlations do not imply anything what causes what
 - *Knowledge is created by seeking good explanations*
 - Bad philosophy will have cause bad science
 - Explanationless theories can do no more than entrench existing bad explanations
 - Explanationless science => science with unstated, uncriticized explanations
 - Consistent definitions cannot be false
 - Results are not conclusive, merely suggestive
 - The substance of scientific theories is explanation and explanation of errors constitutes most of
   the content of the design of any non-trivial scientific experiment
 - Bad philosophy cannot be easily countered by good philosophy
 - Bad philosophy can be countered by progress
 - People want to understand the world, no matter how loudly they may deny that
 - *Progress makes bad philosophy harder to believe*
 - *Bad philosophy is philosophy that denies the possibility, desirability and existence of progress*
 - Progress is the only effective way of opposing bad philosophy
 - If progress cannot continue indefinitely, bad philosophy will inevitably come again into ascendancy - for it will be true


** Choices
   - There is no such thing as mathematical inspiration
   - Science judge evidence with the criterion of good explanation
   - It would be wrong for science to adopt the democratic principle
   - Our knowledge of mathematics is not infallible
   - That which cannot be done perfectly must be done in a manner as near perfection as can be.
   - *No dictator axiom*: The rule must not simply designate the views of one particular person to be the prefereces of
     the group regardless of what others want
   - There is no such thing as the will of the people
   - *If exactness cannot, from the nature of things, be attained then the nearest practicable approach 
      to exactness ought to be made.*
   - Whenever one patches up a decision-making system in one way, it becomes paradoxical in another
   - Rational decision making consists not of weighing evidence, but of explaining it,
     in the course of explaining the world.
   - At the heart of decision making is the creation of new options, and the abandonment
     or modification of existing ones.
   - *To choose an option, is to choose its explanation*
   - The process that adjudicates between the different explanations would have to satisfy certain constraints
     if it were to be rational.
   - *Decision making is problem solving*
   - *To choose an option rationally is to choose the associated explanation*
   - Without the inspiration phase nothing is ever solved and there is nothing to choose between
   - A good explanation is being hard to vary at all without losing its explanatory power is hard
     to mix with a rival explanation
   - *Mixing two explanations to create a better explanation requires an additional act of creativity*
   - Social-choice theory is itself based on false assumptions about what thinking and deciding consist of.
   - *Good explanations are discrete, separated from each other by bad explanations*
   - *A logial contradiction is nonsense*
   - If your conception of justice conflicts  with the demands of logic or rationality then it is unjust.
   - *An impossible wish is ultimately uninteresting as well.*
   - If your conception of rationality conflicts with a mathematical theorem then your conception of 
     rationality is irrational
   - Conditions of fairness -> misconceptions
   - Rational analysis:
     - removal of bad policies and rules
     - creation of new options
   - Society is not a zero-sum game
   - We need something better to wish for
   - *What is necessary for progress is to exclude ideas that fail to survive criticism*
   - Promoting the creation of new ideas is necessary for progress
   - insignificant in comparison with the greater effectiveness
   - Even democracy itself is unworkable under some circumstances
   - *Solutions create new problems*
   - A successful truth-seeking system works its way towards broad consensus or near-unanimity
   - Good policies are hard to vary
   - Conflicting policies are discrete and cannot be arbitrarily mixed.
   - Most important element of decision making => creation of new options
   - It is a mistake to conceive of choice and decision making as a process of selecting from existing
     options according to a fixed formula.



** Why are Flowers Beautiful?


** The Evolution of Culture


** The Evolution of Creativity


** Unsustainable


** The Beginning


