* The Paradox of Choice
Author: Barry Schwartz

** The Paradox of choice - a roadmap
 - We would be better off
   - if we embraced certain voluntary constraints on our freedom of choice, instead of rebelling against them
   - seeking what was "good enough" instead of seeking the best
   - if we lowered our expectations about the results of decisions
   - if the decisions we made were non-reversible
   - if we paid less attention to what others around us were doing
 - Conventional wisdom is wrong at least when it comes to what satisfies us in the decisions we make.

** New Choices
 - Negaitve liberty: freedom from constraint, freedom from being told what to do by others
 - Positive liberty: freedom to the availability of opportunities to be the author of your life and to make it meaningful and significant
 - Negative liberty => freedom from
 - Positive liberty => freedom to
 - *Not all choices enhances freedom*
 - impair freedom
 - Many people are feeling less and less satisfied even as their freedom of choice expands
 - Instead of being fetishistic about freedom of choice, we should ask ourselves whether it nourishes us deprives us
   whether it makes us mobile or hems us in
   whether it enhances self-respect or diminishes it
 - Freedom of choice => core value
 - We do ourselves no favor when we equate liberty too directly with choice, as if we necessarily increase freedom by increasing the no of options available.
 - Liberty !== Choice
 - We make the most of our freedoms by learning to make good choices about the things that matter,
   while at the same time unburdening ourselves from too much concern about the things that don't
 - The range of chioces people face everyday has increased in recent years
 - How we choose and how difficult and demanding it is to make wise choices
 - Maximizers => individuals determined to make only the best choices
 - How and why choice can make us suffer
 - *Increased opportunities for choice actually make people not happier*
 - Added options do not make people better off
 - adaptation, regret, missed opportunities, raised expectations - feelings of inadequacy in comparison with others
 - Increased choice may actually contribute to the recent epidemic of clinical depression
 - A series of recommendation for taking advantage of what is positive and avoiding what is negative in our modern freedom of choice
 - The important lessons to be learned are not so obvious and counterintuitive

** Deciding and Choosing

** When Only the Best will do

** Choice and Happiness

** Missed Opportunities

** If only, the problem of Regret

** Why Decisions Disappoint: The problem of adaptation

** Why Everything Suffers from Comparison

**** Hopes, Expectations, Past Experience, and the Experience of Others

**** Prospects, Frames and Evaluation

**** The Curse of High Expectations

**** The Curse of Social Comparison

**** The Race for Status

**** Status, Social Comparison and Choice

**** Positional Competition

**** Social Comparison: Does everybody do it?

**** Maximizing, Satisficing and Social Comparison

**** Choice options and Social Comparison


** Whose Fault is it? Choice Dissappointment and Depression

** What to do about choice?

*** Choose When to Choose

*** Be a Chooser, Not a Picker

*** Satisfice More and Maximize Less

*** Think About the Opportunity Costs of Opportunity Costs

*** Make Your Decisions Nonreversible

*** Practice and "Attitude of Gratitude"

*** Regret Less

*** Anticipate Adaptation
  - *We adapt to almost everything we experience with any regularity.*

*** Control Expectations
  - Our evaluation of experience is substantially influenced by how it compares with our expectations.
	- *The easiest route to increasing satisfaction with the results of decisions is to remove
		excessively high expectations about them*
	- To make the task of lowering expectations easier:
		- Reduce the number of options you consider
		- Be a satisficer than a maximizer
		- Allow for serendipity

*** Curtail Social Comparison
  - We evaluate the quality of our experiences by comparing ourselves to others.
	- Social comparison often reduces our satisfaction
	- Social comparison seems sufficiently destructive to our sense of well-being that
		it is worthwhile to remind ourselves to do it less.
	- It is easier for a satisficer to avoid social comparison than for a maximizer
	- Learning that "good enough" is good enough may automatically reduce concern with how others are doing
	- *Focus on what makes you happy, and what gives meaning to your life*

*** Learn to Love Constraints
  - As the number of choices we face increases, freedom of choice eventually becomes
		a tyranny of choice.
	- Choice within constraints, freedom within limits, is what enables to imagine a
		host of marvelous possibilities.
