* The Fabric of Reality
The Science of Parallel Universes - and It's implications

Author: David Deutsch

** The Theory of Everything
- Scientific knowledge, like all human knowledge, consists primarily of explanations
- Mere facts can be looked up
- Predictions are important only for conducting crucial experimental tests to discriminate between
  competing scientific theories that have already passed the test of being good explanations
- As new theories supersede old ones, our knowledge is becoming both
  broader ( as new subjects are created) and
  deeper (as our fundamental theories explain more, and become more general).
- Depth is winning
- Our deepest theories are becoming so integrated with one another that they can be understood only jointly,
  as a single theory of a unified fabric of reality.
- This Theory of Everything has a far wider scope than the ' theory of everything' that elmentary
  particle physicists are seeking.
- The Fabric of Reality  does not consist only of reductionist ingredients such as
  - space
  - time
  - subatomic particles
  but also, for example of
  - life
  - thought and
  - computation.
- The four main strands of explanation which may constitute the first Theory of Everything are:
  - quantum physics
  - epistemology
  - the theory of computation
  - the theory of evolution

** Shadows
- The universe we see around us does not constitute the whole of reality.
- In fact the whold of physical reality,the multiverse, constains a vast numbers of parallel universes.

** Problem-solving

** Criteria for Reality

** Virtual Reality

** Universality and the Limits of Computation

** A Conversation About Justification

** The Significance of Life

** Quantum Computers

** The Nature of Mathematics

** Time: The First Quantum Concept

** Time Travel

** The Four Strands

** The Ends of the Universe 
