* The Little Book of Big Dividends
A Safe formula for guaranteed returns
Author: Charles B. Carlson

** Foreword
- Finally - sensible investing made simple
- Never changes his tune to fit fashion or fad
- Since only companies that have profits can afford to consistently pay dividends, these
  stocks have a record of increasing price, as well
- **You can make big money by investing for the long term in dividend-paying stocks.**
- Investing doesn't have to be complicated, expensive, mathematical or time-consuming.
- The market have survived all this hubris
- Now it's time to get back to basics
- The idea of investing for dividends sounds rather quaint
- Even the best and the brightest can't beat the market forever
- the stock market's unprecedented record of long-term growth
- First, you have to understand the importance of dividends to overall total return
- it will require an amazing suspension of disbelief - in this era of instant gratification
- *An extraordinary dividend yield is a dangerous temptation, a warning of trouble ahead*
- Perspective is critical
- Those who strectch for yield without quality will soon learn the truth
- Dividends can provide increasing stipends as the company grows
- Dividend -paying stocks also offer the potential of growth to keep up with inflation
- Don't dismiss the idea of investing for dividends as either hopelessly old-fashioned or totally boring.

** Introduction
- A stock's dividend yield as the interest rate you get for owning a stock
- *There are dividend-paying stocks in today's market that will make you rich*
- today is an excellent time to be a divided investor
- there are tremendous opportunities in dividend-paying stocks
- A stock's yield is determined by two things:
  - the dividend and
  - the stock price
- *Find stocks with above-average appreciation potential and safe and growing dividends,*
  *and buy them at attractive prices*
- Dividend paying stocks are as attractive today as they have been in nearly three decades
- The Importance of size and safety of dividends when considering dividend paying stocks
- BSD (Big Safe Dividends) formula takes into account factors most critical to the safety and growth
  potential of a company's dividend.
- Finding attractive dividend-paying stocks is only one piece of the puzzle. Buying them is another piece.
- *Inflation is the enemy of any investment program*
- One way to help 

** 
** The Check is in the Mail
Get paid to invest with dividends
- *Roughly 40 percent of the stock market's long-run total returns comes from dividends*
*** Why Dividends Matter
- The dependability of dividends is a big reason why investors should consider dividends when buying stock
*** To pay dividends or not to pay dividends
*** No profits, No dividends
*** What's my yield
*** No Free Lunch
*** Dating My Ex
*** Capture the Dividend - Not!
*** Dividends and Taxes

** Supersize me , without the Heart burn
- *Dividend yield is a pretty good proxy for investment yield*

** If Einstein was a Dividend Investor
The Little Formula That Finds the Biggest, Safest Dividends
- Less is usually more when it comes to formulas, including those for investing.
- The fewer moving parts in an investing methodology, the easier it is to implement and monitor.
*** Basic BSD Formula for Stock Selection
The basic formula starts with two simple premises:
1. A company cannot pay dividends if it doesn't have the money to pay dividends
2. You need to choose stocks that have attractive total-return potential, not just dividend returns.

3. BSD formula looks at just two data points:
   1. Payout ratio

   2. Overall Quadrix score
4. Payout Ratio: A stock's payout ratio measures how much of a company's profit is paid out in dividends.
5. Obviously, if a company pays out more in dividends than profits, the dividend will not be sustained.
6. If a company pays out a small portion of its profits in the form of dividends, there's cushion
   for the divided to grow or at least be maintained, even if profits decline.
7. *The payout ratio is perhaps the most powerful tool for getting a quick snapshot of a company's
   *ability to maintain and grow its dividend*


** The World is Your Oyster

** It Pays to be Direct

** The Post Cards from the Hedge
Beat Inflation - and the Stock Market with Dividend Growers
- *No 1. public enemy for investors - inflation*
- inflation - the loss of purchasing power
- Inflation can be devastating for your nest egg
- At an inflation rate of just 3 percent per year, $1 today will Be worth just 50 cents in less than 25 years.
- It is easy to ignore the effects of inflation on future cash flows
- How can income investors fight inflation? Own investments that pay higher income every year.
- One way to hedge against inflation is to focus on stocks that are likely to boost their dividends on a regular basis. The math is simple, but compelling
- The bottom line is that if your dividends can at least keep pace with inflation—and hopefully exceed the inflation rate—your real spending power can be maintained or increased over time.
- Dividend growth may be the best friend of income investors, but it’s often overlooked because income investors focus on today (current yield) and not tomorrow (dividend growth).
- *One way to hedge against inflation is to focus on stocks that are likely to boost their dividends on a regular basis.*
- you’ll increase your chances of owning stocks with attractive capital-gains potential.
- You don’t necessarily need big yields to generate big dividends.
- In fact, in many cases the biggest dividends over time come from moderate yielders that grow their dividends regularly.
- the way individuals typically frame buying decisions.
- *Yield is a good proxy for risk*
- When you move money to a higher-yielding investment, it’s likely you are moving to a higher-risk investment
- Since dividends are paid with cash, they can’t be faked. They can’t be created through accounting magic; either you pay the dividend, or you don’t.
- When a company makes a commitment to pay the dividend, it’s showing confidence that it will be able to continue to pay this commitment to shareholders
- When a company increases its dividend, the firm is saying that it believes the company’s future is strong enough to support an increase in shareholder cash flows.
- A dividend increase is not a perfect signal that the future is bright
- Under most circumstances a company is not likely to raise its dividend without having a high degree of confidence that it can deliver
- *Buying dividend growers is not just a good idea as an inflation hedge; it’s a good idea because dividend growers, as a group, outperform the market.*
***** The Age Old Question: Risk vs Reward
- 33 years is a fairly long period of time to recoup an investment.
- Think of payback as a safety-net approach to stock investing. Obviously, nobody knows for sure how a stock is going to behave over time.
- By calculating a payback period, you help establish an expected baseline performance, kind of a worst- case scenario, for getting your initial investment back.
- Should you focus on stocks that have the quickest payback? Not necessarily. Ultimately, total return is what matters.
- Still, using dividend payback is a worthwhile concept for framing the risk-return potential of two stocks. It’s also a useful tie-breaker when choosing between two investments.
*** Use the Advanced BSD Formula to Find Growers
- An excellent way to zero in on dividend growers is to use the Advanced BSD formula
- Companies that have high BSD scores typically have excellent dividend-growth prospects.
- Advanced BSD formula factors in the most important components of dividend growth:
  - Profit Growth
  - Cashflow Growth
  - Payout ratio
- Profits and cash flow ultimately determine the amount of dividends a company can pay
- if profits and cash flow are rising, dividends should follow. The payout ratio shows the amount of flexibility a company has with its dividend
- A payout ratio of 60 percent ($1 in dividends paid out for every $1.66 in profits) or below reflects a company that is more likely to maintain or boost its dividend than one already paying out most of its profits in dividends.
*** Finish Strong
- In racing parlance, current yield is only the starting line. And as everyone knows, *it’s not how you start a race, it’s how you finish*
- Dividend growth hedges against inflation, accelerates your payback on invest- ment, and tends to point you toward stocks that beat the market
**** Yield
***** Hedge me if you can. Higher dividends are a great inflation hedge.
***** Payback is a pitch for dividend growers. Dividend growth accelerates the payback on your investment.
***** Put on your signal. Companies that increase their dividends signal their confidence in the future—a confidence that should manifest itself in market-beating returns

** LifeGuard on Duty

** Juice your portfolio without striking out

** When DRIPs become Floods

** If you build it, Dividends will come

** Advanced BSD formula

** The Ultimate Bid, Safe Dividend Portfolio
