* The Beginning of Infinity
Author: David Deutsch

Explanations that transform the world

** Introduction
- All progress has resulted from a single human activity, the quest for good explanations.
- Much progress is unbounded.
- Although progress has no necessary end, it does have a necessary beginning.
-
** The Reach of Explanations
- The universe is seething with violent activity.
- Explanations:- assertions about what is out there and how it behaves
- Learning from experience => choose between theories
- inductive inference => general from the peculiar
- Scientific explanations are about reality.
- For if one cannot derive predictions from experience, one certainly cannot derive explanations.
- Since inductivism is false, empiricism must be as well.
- The sens*e cannot be deceptive in themselves.
- What misleads us are only the false interpretations that we place on appearances.
- Justification !== Fallibilism
- Fallibilism is essential for the initiations of unlimited knowledge growth - the beginning of infinity.
- *All observations are theory-laden, and hence fallible, as all our theories are*.
- conjecture - theoretical interpretation
- *We perceive nothing as what it really is*.
- *There is nothing more deceptive than an obvious fact.*
- cimenti = trials by ordeal
- Appearances are not self-explanatory
- *Prediction is not and cannot be the purpose of science*.
- Explanation is a statement of the reality that accounts for the appearance.
- There is no such thing as a purely predictive, explanationless theory.
- *Knowledge that is both familiar and uncontroversial is background knowledge.*
- *Solving a problem means creating an explanation that does not have the conflict.*
- Conflicting ideas in a broader sense are the occasion for all rational thought and inquiry.
- Expectations are theories too.
- There are no contradictions in reality.
- *Every problem signals that our knowledge must be flawed or inadequate*.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- We are born with ideas and with the ability to make progress by changing them.
- Explanation plays the central role in science.
- Prediction alone is insufficient.
- Science is what we have learned about how to keep from fooling ourselves. - Richard Feynman
- Good explanations are often strikingly simple or elegant.
- Removing superfluous features and arbitrariness yields a good explanation.
- Virtually all human attempts to explain experience in terms of a wider reality have indeed been fiction.
- The maxim of testability promotes the growth of knowledge in science.
- A good explanation makes it harder for you to fool yourself
- The better an explanation is, the more rigidly its reach is determined.
- Ideas were static for long periods
- We need explanations to survive
- Apperances are deceptive
- The real source of our theories is conjecture
- The real source of our knowlege is conjecture alternating with criticism
- We interpret our experiences through explanatory theories but true explanations are not obvious.


** Closer to Reality
   - A galaxy is a ming-boggling huge thing. For that matter, a star is a mind-bogglingly huge thing.
   - A human brain is a ming-bogglingly huge thing in terms of both its internal complexity and the reach of human ideas.
   - One can be misled easily and thoroughly.
   - Progress requires the application of ever more knowlege in advance of our observations.
   - The quest for good explanations corrects the errors.
   - Scientific truths consists of such correspondence between theories and physical reality.
   - rare and fragile configurations of matter
   - Our minds, through the methodological criterion conclude that a particular thing is real if and only if it figures in our best explanation of something.
   - *We observe nothing directly. All observations are theory-laden*
   - *The growth of knowledge consists of correcting misconceptions in our theories.*
   - People can apply creativity even to tasks that computers and other machines do it uncreatively.
   - *Science is not mindless toil for which rare moments of discovery are the compensation*
   - The toil can be creative and fun, just as the discovery of new explanations is.
   - Whenever we make an error, it is an error in the explanation of something.



** The Spark
 - Anthropocentric approach has never yielded  any good explanations beyond the realm of human affairs
 - Anthropocentrism - explanatory and geometrical
 - The universe does not even have a geometrical centre
 - Human beings and their wishes and actions are extremely insignificant in the universe at large
 - The patterns of stars and planets in our night sky have no significance for human affairs
 - Living things, including humans, all consist of the same ingredients as rocks and stars, obey the same laws
	 that they were not designed by anyone
 - *People are significant in the cosmic scheme of things*
 - *The Earth's biosphere is incapable of supporting human life*
 - Anthropocentric errors are examples of parochialism, but not all parochialism is anthropocentric.
 - Earth is tiny and ephemeral
 - rich conceptual framework
 - We are uncommon form of ordinary matter
 - Matter
	 - 80% => Dark matter(invisible, neither emit nor absorb light)
	 - 20% => Ordinary matter (glowing continuously)
 - The biosphere is not a great preserver of species
 - The biosphere only ever achieves stability by continually neglecting, harming, disabling and killing individuals.
 - Knowledge was transmitted from generation to generation not genetically but culturally.
 - *It was only human knowledge that made the planet even marginally habitable*
 - They didn't realize anything, because they did not know how to seek better explanations
 - We assumed far too easily that the world was fundamentally incomprehensible to them
 - Evolution did not waste our resources on detecting phenomena that were never relevant to our survival
 - Human attributes evolved under natural selection in an ancestral environment
 - *Technology progess has depended specifically on the creation of explanatory knowledge.*
 - The increasingly intimate connection between explaining the world and controlling it is not accident, but is
	 part of the deep structure of the world
 - *All regularities in nature have explanations*
 - People -> entities that can create explanatory knowledge
 - *Humans can create and apply new knowledge*
 - We are accustomed to thinking of the Earth as hospitable
 - Every cell is a chemical factory
 - The opportunities provided by the laws of nature for transforming resources are universal
 - human bodies - universal constructors
 - *The only uniquely significant thing about humans is our ability to create new explanations*
 - Moral knowledge -> knowledge about what to want and what to strive for
 - *Human reach is the same as the reach of explanatory knowledge itself*
 - The human mind seeks explanations and now that we know how to find them, we are not going to stop voluntarily
 - The laws of physics forbid the creation of energy from nothing
 - *Humans are universal constructors*
 - *An unproblematic state is a state without a creative thought*
 - unproblematic state = death
 - All the fundamental constants of nature can be measured here
 - Every fundamental law can be tested here
 - Every problem of finding or transforming resources can be no more than a transcient factor limiting the creation of knowledge in a given environment
 - Matter, energy and evidence are the only requirements that an environment needs to have in order to be a venue for open-ended knowledge creation
 - *There has never been an unproblematic time for humans* That applies as much to the future as to the past
 - *There can be no such thing as an ultimate explanation*
 - *Problems are inevitable*
 - *Problems are soluble*
 - Humans are capable of attaining a state of supposed perfection
 - *Every attainable state can be indefinitely improved*
 - Our values and our objectives can continue to improve indefinitely
 - Earth is inundated with matter, energy and evidence
 - In the universe at large, knowledge friendliness is the rule not the exception
 - The fundamental laws of nature are so uniform and evidence about them so ubiquitous
 - Knowledge is a significant phenomenon in the universe
 - Non-explanatory knowledge cannot be universal
 - Proxy => a physical variable which can be measured as a way of measuring another variable
 - *All scientific measurements involve a chain of proxies*
 - Human, people and knowledge are not only objectively significant. They are by far the most significant phenomenon in nature
 - *All knowledge creating systems correct errors*
 - Universality and reach are inherent in the laws of nature
 - People are universal constructors
 - *New explanations create new problems*
 - *Everything that is not forbidden by laws of nature is achievable, given the right knowledge*
 - 


** Creation
 - Good adaptations are distinguished by being hard to vary while still fulfilling their functions.
 - Knowledge is very unlikely to come into existence other than through the error correcting processes of evolution or thought.
 - Knowledge:
	 - Biological
	 - Explanatory
 - Some historic misconceptions about biological evolution have counterparts in misconceptions about human knowledge.
 - Who designed the designer?
 - *A good design is hard to vary*
 - Knowledge must be first conjectured and then tested
 - Evolution optimises neither the good of the species nor the individual.
 - Not all evolution constitutes progress and no(genetic) evolution optimizes progress
 - Organisms are the slaves, tools that genes use to achieve their purpose of spreading themselves throughout the population
 - Nearly all long lasting ideas are memes
 - Ideas can be replicators too
 - Memes => ideas that are replicators
 - No human knowledge is entirely non-explanatory
 - People often try to improve explanations even when they have received them accurately
 - People rarely express ideas in exactly the same words in which they heard them
 - *Good explanations are hard to vary*
 - The existence of an unsolved problem in physics is no more evidence for a supernatural explanation
 - Prediction changes radically if there are several constants to explain
 - There are infinitely many logically possible laws of physics
 - Almost random states are by far the most numerous
 - Specific explanation in terms of specific laws of nature is needed
 - An idea so simple, that we will all say to each other, how could it have been otherwise
 - Scientific discovery is profoundly unpredictable, despite the fact that it is determined by the laws of physics
 - Genes and ideas are both replicators
 - Knowledge and adaptations are both hard to vary
 - *Human knowledge can be explanatory and can have great reach*
 - The problem has been no that the world is so complex that we cannot understand why it looks as it does,
	 but it is that it is so simple that we cannot yet understand it.
 - Adaptations are never explanatory  and rarely have much reach beyond the situations in which they evolved.

** The Reality of Abstractions
 - *Guiding Principle* - Always reject bad explanations in favor of good ones
 - Emergent phenomena are essential to the explicability of the world
 - All knowledge creation depends on and physically consists of emergent phenomena.
 - *The explanation in one field affects our understanding of other fields*
 - We can let our theories die in our place
 - Abstractions are essential to a fuller explanation
 - myopic to the point of silliness
 - *Empiricism has multiple fatal flaws*
 - Criticism is correspondingly effective
 - The growth of knowledge does not consisting of finding ways to justify one's beliefs. It consists of finding good explanations
 - *The truth has structural unity and logical consistency*
 - Factual knowledge can be useful in criticising moral explanations
 - *There is an objective difference between right and wrong*
 - There is such a thing as objective beauty
 - There is no avoiding what-to-do-next problems
 - *Progress depends on explanation*
 - Trying to conceive of the world as merely a sequence of events with unexplained regularities would entail giving up on progress
 - Explanations do not form a hierarchy
 - Our knowledge of abstractions comes from the fact that our best explanations invoke them


** The Jump to Universality
 - Innovation is unpredictable
 - The largest benefits of any universality come from its begin useful for further innovation
 - *Progress is both desireable and attainable*
 - Universality is both desireable and attainable
 - Universality was being sought deliberately as a desireable feature in its own right
 - because of the usual lack of interest in universality
 - Physical objects are unlike each other and dominated by different laws of physics can exhibit the same mathematical relationships
 - tragic might-have-beens of history
 - The history of electronic technology since 2nd world war was dominated by miniaturization
 - *Error-correction is the beginning of infinity*
 - It is in the very nature of analogue computation that every value could be correct
 - Analogue computation can never be universal
 - All universal computers are digital and all use error-correction with the same basic logic
 - In reality, information that cannot be reliably retrieved is not really being stored.
 - The limitation that the information being processed must be digital does not detract from the universality of digital computers or of the laws of physics
 - It is just a matter of approximating continuously variable quantities by a sufficiently fine grid of discrete ones
 - The laws of physics are such that the behavior of any physical object can be simulated with any desired accuracy by a universal computer
 - Reach always has an explanation
 - People are universal explainers and universal constructors
 - *All knowledge growth is by incremental improvement*
 - Universal computers cannot really be universal unless there are people present to prove energy and maintenance indefinitely
 - Even life on Earth will eventually be extinguished unless people decide otherwise
 - Only people can rely on themselves into the unbounded future
 - *The jump to universality*: The tendency of gradually improving systems to undergo a sudden large increase in functionality becoming universal in some domain
 - Error-correction is essential in the process of potentially unlimited length
 - *The jump to universality only ever happens in digital systems*


** Artificial Creativity
 - quale - the subjective aspect of sensations
 - Qualia are currently neither describable nor predictable
 - a constellation of attributes
 - If you can't program it, you haven't understood it.
 - It is very rare for practical solutions to fundamental problems to be discovered without any explanation of why they work
 - Becoming better at pretending to think is not the same as coming closer to being able to think
 - The theory of evolution does not have to account for why every specific mutation succeeded or failed in the history of a given adaptation
 - AI abilities must have some sort of universality
 - Every AI is a person: a general purpose explainer
 - The ability to imitate a human imperfectly or in specialized functions is not a form of universality
 - stimuli = external circumstances; responses = observed behaviors
 - *Progress requires alternating inspiration and perspiration phases*
 - Biological evolution often reaches local maxima of fitness
 - jump to universality
 - We do not know why the DNA code has enough reach
 - *We do not understand how creativity works*
 - constellation of associated attributes
 - We do not understand the nature of the universality of the DNA replication system


** A Window on Infinity
 - Argument from personal incredulity => a preference for parochial misconceptions over universal truths
 - *Finitism is inherently anthropocentric*
 - Many facts about finite things are just as counter-intuitive
 - Law of the excluded middle: For every meaningful proposition, either it or its negation is true
 - Space was usually regarded as a continuum
 - *Even a finite line is composed of infinitely many points*
 - Beginning of infinity => a condition where progress in the future will be unbounded
 - Beginning of infinity => a condition where an infinite amount of progress will be made
 - Finitism regards parochialism as a virtue of a theory rather than a vice.
 - All abstract theorizing is theory laden too
 - Finite is parochial
 - *The best explanation of anything eventually involves universality and infinity*
 - The reach of explanations cannot be limited by fiat.
 - intuitions about infinity are often illogical
 - Not all infinities are equal
 - Larger infinities are called uncountable
 - Countable infinity => an infinity that is small enough to be placed in one-to-one correspondence with natural numbers
 - *Infinity is not magic; it has logical rules*
 - No theory explains everything
 - The beginning of infinity is one of the attributes of the unbounded growth of knowledge
 - We are only just scratching the surface and shall never be doing anything else
 - probable or improbable, rare or common, typical or untypical attributes have literally no meaning in regard to
	 comparing infinite sets of natural numbers
 - *Anthropic reasoning by itself cannot make any predictions*
 - Anthropic reasoning can't explain the fine-tuning of the constants of physics
 - We only every experience symbols
 - Quantum theory describes a multiverse and provides a measure for universes
 - Something is definitely finite if it could in principle be encompassed by a human experience
 - Physics deal in distances, not numbers of points
 - *Only the laws of physics determine what is finite in nature*
 - The laws of physics are consistent
 - The laws of physics determine the distinction not only between rare and common, probable and improbable,
	 fine-tuned or not, but even finite and infinite
 - Almost all mathematical truths have no proofs
 - Almost all mathematical truths are unprovable truths
 - Almost all mathematical statements are undecidable. Each of them is either true or false
 - The laws of physics provide us with only a narrow window through which we can look out on the world of abstractions
 - Abstracts exist objectively
 - The laws of physics support computational universality
 - Only the laws of physics that determine which abstract entities and relationships are modelled by physical objects
 - Infinite makes sense mathematically, so why not infinite proofs?
 - *Mathematics seek not random truths, but good explanations*
 - Real proof is independent of physics
 - Proof theory => computer science
 - There is no such thing as abstractly proving something
 - There is no such thing as abstractly knowing something
 - Mathematical truth is absolutely necessary and transcendent
 - All knowledge is generated by physical processes and its scope and limitations are conditioned by the laws of nature
 - The whole motivation for seeking a perfectly secure foundation for mathematics was mistaken.
 - The object of mathematics is to understand - to explain - abstract entitites
 - *Proof is a primary means of ruling out false explanations*
 - The whole point of universality is lost, if one conceives of computation as beign somehow prior to the physical world generating its laws
 - One does not understand a mathematical proposition by merely proving it true
 - *Problems are conflict between ideas*
 - Most mathematical questions that exist abstractly are uninteresting
 - Mathematical knowledge does not consist only of proofs
 - *We cannot create knowledge other than the fallible method of conjecture and criticism*
 - Fallibilism tells us that we can be mistaken about what is interesting
 - Errors are inevitable
 - We cannot prophesy; we cannot predict the content of ideas yet to be created or their effects
 - The problems are soluble does not mean that we already know their solutions or can generate them to order
 - *Only error correcting processes can succeed or continue for long*
 - *There are truths about the physical world that we shall never know*
 - limitations:
	 - directly imposed by the universal laws of physics
	 - epistemology
 - The unpredictability of the content of our future knowledge is a necessary condition for the unlimited growth of that knowledge
 - We can understand infinity through the infinite reach of some explanations


** Optimism
 - The possibilities that lie in the future are infinite
 - It is  our duty to remain optimists
 - All of us contribute to future by everything we do
 - *We are all responsible for what the future holds in store*
 - openness of the future
 - It is our duty not to prophesy evil, but , rather to fight for a better world
 - *Our own future will be shaped by knowledge that we do not yet have*
 - We cannot even predict most of the problems that we shall encounter or most of the opportunities to solve them
 - *Observations are theory laden*
 - Blind optimism is a stance towards the future
 - Both the original optimism and original pessimism are close to pure pessimism
 - Moods do not necessitate any particular stance about the future
 - Blind pessimism - precautionary principle
 - A single catastrophic consequence of an otherwise beneficial innovation could put an end to human progress for ever
 - *The good can be unlimited*
 - The harm that can flow form any innovation that does not destory


** A Dream of Socrates


** The Multiverse


** A Physicist's History of Bad Philosophy


** Choices


** Why are Flowers Beautiful?


** The Evolution of Culture


** The Evolution of Creativity


** Unsustainable


** The Beginning


