* The Little Book of Big Dividends
A Safe formula for guaranteed returns
Author: Charles B. Carlson

** Foreword
- Finally - sensible investing made simple
- Never changes his tune to fit fashion or fad
- Since only companies that have profits can afford to consistently pay dividends, these
  stocks have a record of increasing price, as well
- **You can make big money by investing for the long term in dividend-paying stocks.**
- Investing doesn't have to be complicated, expensive, mathematical or time-consuming.
- The market have survived all this hubris
- Now it's time to get back to basics
- The idea of investing for dividends sounds rather quaint
- Even the best and the brightest can't beat the market forever
- the stock market's unprecedented record of long-term growth
- First, you have to understand the importance of dividends to overall total return
- it will require an amazing suspension of disbelief - in this era of instant gratification
- *An extraordinary dividend yield is a dangerous temptation, a warning of trouble ahead*
- Perspective is critical
- Those who strectch for yield without quality will soon learn the truth
- Dividends can provide increasing stipends as the company grows
- Dividend -paying stocks also offer the potential of growth to keep up with inflation
- Don't dismiss the idea of investing for dividends as either hopelessly old-fashioned or totally boring.

** Introduction
- A stock's dividend yield as the interest rate you get for owning a stock
- *There are dividend-paying stocks in today's market that will make you rich*
- today is an excellent time to be a divided investor
- there are tremendous opportunities in dividend-paying stocks
- A stock's yield is determined by two things:
  - the dividend and
  - the stock price
- *Find stocks with above-average appreciation potential and safe and growing dividends,*
  *and buy them at attractive prices*
- Dividend paying stocks are as attractive today as they have been in nearly three decades
- The Importance of size and safety of dividends when considering dividend paying stocks
- BSD (Big Safe Dividends) formula takes into account factors most critical to the safety and growth
  potential of a company's dividend.
- Finding attractive dividend-paying stocks is only one piece of the puzzle. Buying them is another piece.
- *Inflation is the enemy of any investment program*
- One way to help 

** 
** The Check is in the Mail

** Supersize me , without the Heart burn
- *Dividend yield is a pretty good proxy for investment yield*

** If Einstein was a Dividend Investor

** The World is Your Oyster

** It Pays to be Direct

** The Post Cards from the Hedge

** LifeGuard on Duty

** Juice your portfolio without striking out

** When DRIPs become Floods

** If you build it, Dividends will come

** Advanced BSD formula

** The Ultimate Bid, Safe Dividend Portfolio
