* Thinking in Systems
Author: Donella H.Meadows

- Systems thinking transcends disciplines and cultures
- When done right, systems thinking overarches history as well
- natural systems thinkers
- All books are biased and incomplete
- A basic ability to understand and to deal with complex systems
- *Listen to the Universe!*
- *Let's face it! The universe is messy*
- Getting models out into the light of the day, making them as rigorous as possible,
  testing them against the evidence, and being willing to scuttle them if they are no longer
  supported is nothing more than practising the scientific method.
- the rationality
- the systematic patterns of thought
- Duality:
  - We know a tremendous amount about how the world works, but not nearly enough.
  - Our knowledge is amazing; our ignorance is even more so
  - We can improve our understanding but we can't make it perfect.
- Once we see the relationship between structure and behaviour, we can begin to understand how systems work

** Part One: System structure and behavior

*** Introduction: The System Lens
  - Managers do not solve problems, they manage messes.
  - The system may be buffetted, constricted, triggered or driven by outside forces.
  - better behavior patterns
  - Systems thinking is a way of thinking that gives us the freedom to identify root causes of problems and see new opportunities
  - A system is a set of things interconnected in such a way that they produce their own pattern of behavior over time.
  - *The system to a large extent causes it's own behavior*
  - part of a larger set of influences and societal issues
  - deeply unsettling
  - a resistance to and a recognition of systems principles
  - feedback delays
  - competitive exclusion principle:
    - If a reinforcing feedback loop rewards the winner of a competition with the means to win further competitions,
      the result will be the elimination of all but a few competitors
  - *A diverse system with multiple pathways and redundancies is more stable and less vulnerable to external shock
    than a uniform system with little diversity*
  - out there vs in here
  - It's almost irresistible to blame something or someone else to shift responsibility away from ourselves
  - We must do things, or atleast see things and think about things in a different way.
  - Systems happen all at once
  - reductionist unholistic way
  - Feedback loop => the basic operating unit of a system
  - the tragedy of the commons
  - eroding goals
  - intrinsically systems problems
  - *Archetypes* => common structures that produce characteristic behaviors
  - *The systems thinking lens allows  us to reclaim four intuition about whole systems.*
  - We can learn how to look for leverage points for change
  - Archetypes are responsible for some of the most transigent and potentially dangerous problems
  - Archetypes can also be transformed, with a little systems understanding, to produce much more desirable behaviors
  - Each way of seeing allows our knowledge of the wondrous world in which we live to become a little more complete
  - The behavior of a system cannot be known just by knowing the elements of which the system is made

*** The Basics
 - system:
   - elements
   - interconnections
   - function or purpose
 - coherently organized
 - You can't see the forest for the trees
 - It's easier to learn about a system's elements than about its connections.
 - Many of the interconnections in systems operate through the flow of information. Information holds systems together and plays a great role in determining how they operate.
 - Purposes are deducted from behavior, not from rhetoric or stated goals.
 - Systems can be nested within systems.
 - One of the most frustrating aspects of a system is that the purposes and subunits may add up to an overall
   behavior tha no one wants.
 - Keeping sub-progress and overall system purposes in harmony is an essential function of successful systems.
 - *Changing interconnections in a system can change it dramatically*
 - Changes in function for purpose can also be drastic
 - an unsystematic question
 - A change in purpose changes a system profoundly, even if every element and interconnections remain the same.
 - *The least obvious part of the system, its function or purpose, is often the most crucial determinant of the system's behavior.
 - Storing information means increasing the complexity of the mechanism.
 - Stocks change over time through the actions of a flow.
 - *All models, whether mental models or mathematical models are simplifications of the real world*
 - A stock can be increased by decreasing it outflow rate as well as by increasing its inflow rate.
   There's more than one way to fill a bathtub.
 - A stock takes time to change, because flows take time to flow.
 - People often underestimates the inherent momentum of a stock.
 - Changes in stocks se the pace of the dynamics of systems.
 - *Stocks generally change slowly, even when the flows into or out of them change suddenly.
   Therefore stocks act as delays or buffers or shock absorbers in systems.
 - You can use the opportunities presented by a system's momentum to guide it toward a good outcome.
 - *Stocks allow inflows and outflows to be decoupled and to be independent and temporarily out of balance with each other.*
 - Everything we do as individuals, as an industry or as a society is done in the context of an information-feedback system
 - ebbs and flows
 - successes and problems
 - *System thinkers see the world as a collection of feedback processes*
**** How the System Runs itself - Feedback
- First hint of the existence of a feedback loop => the consistent behavior pattern over a long period of time.

*** A Brief Visit to the Systems Zoo

** Part Two: Systems and Us

*** Why Systems Work so Well

*** Why Systems Surprise Us

*** System Traps ... and Opportunities

** Part Three: Creating Change - in Systems and in Our Philosophy

*** Leverage Points - Place to Intervene in a System

*** Living in a World of Systems
