* Common Stocks and Uncommon Profits and other writings 
Author: Philip A. Fisher

** Common Stocks and Uncommon Profits

*** Clues from the past

*** What 'Scuttlebutt' can do

*** What to Buy: The 15 points to look for in a common stock

**** Does the company have products or services with sufficient market potential to make possible a sizable increase in sales for at least several years?

**** Does the management have a determination to continue to develop products or processes that will still further increase total sales potentials
when the growth potentials of currently attractive product lines have largely been exploited? 

**** How efffective are the company's research and development efforst in relation to its size?

**** Does the company have an above average sales organization?

**** Does the company have a worthwhile profit margin?

**** What is the company doing to maintain or improve profit margin?

**** Does the company have outstanding labor and personnel relations?

**** Does the company have outstanding executive relations?

**** Does the company have depth to its management?

**** How good are the company's cost analysis and accounting controls?

**** Are there other aspects of the business, somewhat peculiar to the industry involved, which will give the investor important clues as to how
outstanding the company may be in its relation to the competition?

**** Does the company have a short-range or long-range outlooks in regard to profits?

**** In the foreseeable future, will the growth of the company require sufficient equity financing so that the large number of shares then outstanding
will largely cancel the existing shareholder's benefit from this anticipated growth?

**** Does the management talk freely to the investors about its affairs when things are going well but "clam up" when troubles and disappointments occur?

**** Does the company have a management of unquestionable integrity?

*** When to buy

*** When to Sell: And when not to 

*** The Hullabaloo about Dividends

*** 5 don'ts for investors

*** 5 more don'ts for investors

*** How I go about finding a growth stock

** Conservative Investors sleep well

*** The First dimension of a conservative investment
*** The Second dimension of a conservative investment
*** The Third dimension of a conservative investment
*** The Fourth dimension of a conservative investment
*** More about the fourth dimension
*** Still More about the fourth dimension

** Developing an Investment Philosophy

*** Origins of a Philosophy

****** The Birth of Internet

****** Formative Experiences

****** First lessons in the school of experience

****** Building the Basics

****** The Great Bear Market

****** A Chance to to My Thing

****** From Disaster, Opportunity Springs

****** A Foundation is Formed
